### ISSUE TITLE
discrepancy in adding new variant issues

### ISSUE THREAD

**Issue by ralfharing** [GrandComicsDatabase/gcd-django#10]
There is a slight difference in functionality between when users can add variant issues. The assumed base case is that someone else (user X) has an issue reserved. The discrepancy exists depending on whether the issue has a cover uploaded or not.

If there is a cover uploaded, then user Y can visit the "edit covers" link and add a new variant (assuming they have a cover image to upload).

If there is no cover uploaded, then user Y cannot add a new variant.

It would seem desirable for users to be able to add variants at any time, regardless of the state of the base issue and independent of having a cover image for the new variant. Tests on beta show that taking an issue reserved to user X, user Y can manually go to http://www.comics.org/issue/<issueID>/add_variant_issue and submit the form for a new variant successfully. The "submit new variant and edit base issue" box correctly errors out, but should probably not be shown as it is always inapplicable when the base issue is reserved elsewhere.

**Comment by jochengcd** [comment]
2c05e1da1ed5819ecd2fbd65b7d6b67e683ac9e8
