### ISSUE TITLE
Our session mgmt is incompatible with JSON serialization in Django 1.6

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#102]
Bug found by Peter Croome

JSON serialization, rather than pickle, became the default in 1.6 and is generally recommended for security reasons.

A temporary workaround is to set the serializer back to pickle, but we should figure this out at some point.

This happens when trying to add a reprint link.  The stack trace is entirely in Django code, through the session middleware.  The callback function for the middleware is our add_reprint() function.

```
TypeError at /story/revision/5859435/add_reprint/2487878/
<django.http.response.HttpResponseRedirect object at 0x7f09daa7ea10> is not JSON serializable
Request Method: GET
Request URL:    http://beta.comics.org/story/revision/5859435/add_reprint/2487878/?reprint_5859435=Add+reprint
Django Version: 1.6.11
Exception Type: TypeError
Exception Value:
<django.http.response.HttpResponseRedirect object at 0x7f09daa7ea10> is not JSON serializable
Exception Location: /usr/lib/python2.7/json/encoder.py in default, line 178
Python Executable:  /usr/bin/python
Python Version: 2.7.3
Python Path:
['/opt/env/gcd_production/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/var/www/gcd-django',
 '/opt/env/gcd_production/lib/python2.7/site-packages',
 '/opt/env/baseline/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/opt/env/baseline/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/opt/env/baseline/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/opt/env/baseline/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/opt/env/baseline/lib/python2.7',
 '/opt/env/baseline/lib/python2.7/plat-linux2',
 '/opt/env/baseline/lib/python2.7/lib-tk',
 '/opt/env/baseline/lib/python2.7/lib-old',
 '/opt/env/baseline/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/opt/env/baseline/local/lib/python2.7/site-packages',
 '/opt/env/baseline/lib/python2.7/site-packages']
Server time:    Thu, 15 Oct 2015 22:48:57 +0000
```

**Comment by jochengcd** [comment]
Reading up on this, in our situation we are fine with PickleSerializer. The security issue arises with cookie-based sessions, but we use db and cached based session: django.contrib.sessions.backends.cached_db

see further: https://docs.djangoproject.com/en/1.11/topics/http/sessions/, e.g.
Cookies contain a session ID – not the data itself (unless you’re using the cookie based backend).

Therefore, without access to the data, attackers cannot "pickle" something into the session data. We want to store more complicated django/python objects into the session, so just with the JSON-serializer this is not easily done.

In all, the security problem does not arise for us. I will add a comment in the settings.py to not switch from our session setting, unless we switch the serializer.
