### ISSUE TITLE
reordering series with deleted issues

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#103]
When reordering a series with deleted issues there can be problems (internal server errors) due to their sort_code interfering in the sorting process. Workaround is increasing the sort_codes of deleted issues when such a server occurs. Maybe doing this when deleting issues should be done, although that not fully solves this, but maybe makes it rarer.

**Comment by bookcats** [comment]
Another workaround would be to give the re-orderer the option to change the sort codes of the deleted issues when the internal server error occurs (or even include them in the list but crossed out so the reorderer knows they are deleted). The reorder function is editor only, so I think we would accept a bit of weirdness.

**Comment by handrews** [comment]
IIRC, the code only uses the sort codes you enter as relative codes- it doesn't save them as-is to the database, instead it is supposed to grab a block of available numbers that produces the same effect as the order you put in (it's not as complicated as it sounds).  I'm willing to bet that whatever it does to find the open block of codes just fails to take deleted issues into account.

Although I might be wrong- I haven't looked at that code in 5 years.

**Comment by shoebutton** [comment]
Can the sort code on deleted issues be nulled or zeroed? Can deleted issues
be moved to a different series (a deleted issues series) so they don't
affect the live issues in the series?

**Comment by handrews** [comment]
Glancing through the code, it's pretty clear that we always use "active_issue" when working with reordering.  I'm pretty sure all that's needed is a bit of logic to always shove deleted issues to the end.

The sort code plus series id must be unique together, so we can't null them out or set them to zero.  Moving them to a deleted issues series would actually be more complicated if we ever want to re-examine deleted issues.  Then we'd have to go digging through revisions to find things that *were* part of series X but are *now* part of the deleted series... it's just easier to shove deleted issues to the end, I'm pretty sure.

**Comment by jochengcd** [comment]
What makes it a bit more difficult is that the reorder_children works for both issues and stories. That is the routine we need to tackle and not think to issue specific.
