### ISSUE TITLE
Creator add: too many fields required

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#104]
Attn: @jadavbheda

The add creator form has many required fields.  However, we will often only have some information about a creator.  And a source field should never be required if no value is submitted for the matching data field.

I don't see this addressed directly in the spec, so for now can we just go with only the fields that can't be null in the database being required?  That will make testing easier.  We can discuss what should be required on the specifications list.

**Comment by ddmilne** [comment]
I’ve worked some with the data entry form on beta and I believe we need only 2 required fields:
	Name
	Name Type
It is quite possible that we will have no other information for some creators.

Also, all the other fields are relevant ONLY for Names tagged as type GCD Official Name or Shop Name.  Therefore, they should not allow data entry for other Types of names, and probably should display grayed out.

I think the data entry screen would be best if it began with only the Name” and “Name Type” fields available for entry.  If Name Type is chosen is GCD Official Name or Shop Name, then data entry could be turned on and continue in the other fields, but they would not be required.  If Name Type is chosen as anything else, then data entry for that name would be done.

- Don Milne

**Comment by handrews** [comment]
Do you actually want additional rows of data for the other fields for each shop name?  I interpreted the spec as saying there is one creator record (where most of the fields live) with many name records attached to it (name + name type), one of which is the "GCD Official Name".

**Comment by jochengcd** [comment]
The spec is (at least to me) quite clear in that there are several name records per creator, e.g. no additional rows of data per shop name as Henry said. We need an additional name table which consists of the first 7? fields of the spec.

**Comment by ddmilne** [comment]
Resolved in final submitted code; only Name field is required.  Tested 6/3/2016, by Don Milne.
