### ISSUE TITLE
"old" search problems

### ISSUE THREAD

**Issue by shoebutton** [GrandComicsDatabase/gcd-django#106]
on beta, the Everything search still works, but the other searches (series, credits, etc) fail on searches with a space in them. In the search URLs, the spaces are converted to '%2520' instead of '%20'. "old" searches work as expected when there are no spaces in the search term.

@jadavbheda

**Comment by jochengcd** [comment]
Due to django 1.6 change of behaviour.

We should only include @jadavbheda when the errors are creators-related.

**Comment by handrews** [comment]
This is fixed on beta (by a commit from @jochengcd ) and will be in the next production deployment.
