### ISSUE TITLE
creator search problems

### ISSUE THREAD

**Issue by shoebutton** [GrandComicsDatabase/gcd-django#107]
on beta, searching for a Creator returns an internal server error @jadavbheda

**Comment by jochengcd** [comment]
The problems arises when USE_ELASTICSEARCH=True, searching works when USE_ELASTICSEARCH=False. 
There needs to be a check 
if sqs == None:
for the creator fields, or these get integrated into the if-branch before with 
if (class_ in (Series, BrandGroup, Brand, IndiciaPublisher, Publisher)):

**Comment by jochengcd** [comment]
this seems to be long fixed
