### ISSUE TITLE
issues with deleted variants show wrong count in issue list

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#108]
See e.g. http://www.comics.org/issue/23258/

There used to be a variant, which by now moved to a separate issue. In the dropdown for selecting other issues there shows a *2. This is due to
def active_base_issues_variant_count(self):
        issues = self.active_base_issues()
        issues = issues.annotate(variant_count=Count('variant_set'))
        return issues

django 1.8 has conditional aggregation which should allow to fix this by further filtering
https://docs.djangoproject.com/en/1.8/ref/models/conditional-expressions/#conditional-aggregation

**Comment by bookcats** [comment]
Related to #127 ?

**Comment by jochengcd** [comment]
#208
