### ISSUE TITLE
UnicodeDecodeError when deleting item from collection with non-ASCII name

### ISSUE THREAD

**Issue by adia** [GrandComicsDatabase/gcd-django#110]
When an item is deleted from a collection with non-ASCII characters in its name, the following exception occurs:

File "/var/www/gcd-django-my-comics/apps/mycomics/views.py", line 265, in delete_item
    _("Item removed from %s" % collection))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 18: ordinal not in range(128)

**Comment by jochengcd** [comment]
actually fixed for a while in 731094aff7c775c4c35d2357ea4cc4d83a70d045
