### ISSUE TITLE
Change highlighting / IMPs may incorrectly think m2m fields have changed

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#117]
Currently, our generic change-checking code compares querysets.  This does what we want, mostly, but it always makes them appear to be changed.  It's not immediately clear whether it is better to switch the generic code to use sets or whether to handle this only at the change highlight / IMP level.

It seems best to wait until we've figured out what both use cases look like before switching this back and forth.  This bug report is to remind me to investigate this.

**Comment by jochengcd** [comment]
Fixed at some point during the refactor, I think.
