### ISSUE TITLE
Django report builder

### ISSUE THREAD

**Issue by shoebutton** [GrandComicsDatabase/gcd-django#121]
Henry recommends that (once he gets to a deployable stage of the cleanup with Django 1.7 or higher) we install this and give the board access:

https://github.com/burke-software/django-report-builder

**Comment by jochengcd** [comment]
there is a test install on beta.comics.org

Lionel, you should have access to it since you have staff status, other board members only if they have staff status.

**Comment by jochengcd** [comment]
There is a test install for almost a year on beta. Seems like we don't want it.

**Comment by jochengcd** [comment]
no uptake from board.
