### ISSUE TITLE
Comment tracking (especially finding comments on other people's indexes)

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#124]
From Flashjay:

I'm mostly concerned with comments I add to other peoples "edits".
While any comments generated within my own edits will be reachable via the issue approved tab in the longer term but when on pending active comments made by other people might be overlooked when they first come in.

A Comments tab that acted in a similiar way to the Approved tab so you have:

Changeset   Current Data    Approver    Last Activity
issue   Title (x series) # x
Name    2016-04-10 21:52:40

Approver would become "Last comment by" (or similiar) and if any concern of seeing a persons profile make their "Name" in plain text rather than a link to it (but given the limited scope of info and ease of finding them...).

So any active comments threads would appear at the top and any old would end up viewable history.

I do miss the odd new comment back to me when I have things on pending, so better notification within the editing panel would help there. If this is just a visual clue on the editing tab (Last Comment date/time column) or just have them added to the Comments tab in a different colour or 2 tabs In/Out?

**Comment by bookcats** [comment]
Also see #153
