### ISSUE TITLE
Deleted variants are counted in issue drop-down

### ISSUE THREAD

**Issue by adia** [GrandComicsDatabase/gcd-django#127]
The drop-down issue select box includes deleted issues in the variant counts of issues with variants. For example:

http://www.comics.org/issue/27349/

This issue has one active and one deleted variant, but the drop-down displays "3 *3" instead of "3 *2".

I believe there's a problem in [active_base_issues_variant_count()](https://github.com/GrandComicsDatabase/gcd-django/blob/b1d56cf628bda3098d3ca45614b834e3dc7301b7/apps/gcd/models/series.py#L151).

**Comment by jochengcd** [comment]
#108
