### ISSUE TITLE
Bug 634: Cannot specify start_date and end_date with 00 for day

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#132]
http://dev.comics.org/bugs/show_bug.cgi?id=634
Reporter: Allen Ross

Over on Gormuu's DC Archives message board, there was discussion about
displaying all the covers for a particular year and month. I figured out how to
do it using advanced search, but there is a bug that prevents me from doing it
properly.

Just go to Advanced Search, and pick Search For: Covers, then try to fill in a
Start Date of 1961.06.00 and an End Date of 1961.06.30.  But it won't work, as
it doesn't like a day of 00.

But to pick up all the covers, one MUST use a Start Date of 1961.06.00, as
there are issues in that range that have the keydate set to 1961.06.00 (such as
Action and Adventure), which is what we are supposed to be setting as the
keydate for issues that ship monthly.  If you set the Start Date field to
1961.06.01, it works, but misses the issues with the 1961.06.00 keydate set (it
shows the issues that have the older keydate of 1961.06.10).

There is a workaround for this; for the Start Date, use the last date of the
previous month: 1961.05.31.  But this still should work without the user
needing to know that.  So either allow 00 for the day, or under the covers
convert a 01 day into a 00 day (the latter would probably be friendlier yet to
the end user).

**Comment by jochengcd** [comment]
I always assumed that the original reporter looked into this and considered the fix somewhat more involved.
