### ISSUE TITLE
Bug 635: No "beta" banner on beta admin site

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#134]
http://dev.comics.org/bugs/show_bug.cgi?id=635
Reporter: Lionel English

http://beta.comics.org/admin/voting/ does not have the "This is beta"
disclaimer banner seen on other pages on beta.

**Comment by jochengcd** [comment]
admin-site uses django templates, not really under our control, as in, we don't want to hack these.
