### ISSUE TITLE
preview for issue adds fails

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#139]
When previewing an issue add (likely also for other adds) the preview fails due to the change to the change_history position/treatment:

NoReverseMatch: Reverse for 'change_history' with arguments '()' and keyword arguments '{'model_name': u'issue', 'id': ''}' not found.

**Comment by handrews** [comment]
How did that work before?  I'm pretty sure I did not change the url tag at all, just moved it :-/

**Comment by handrews** [comment]
I've applied a hotfix in production and submitted the code for review.
Looking at a preview in production, it appears to be fixed (and of course it appeared fixed in my local environment before that).

**Comment by handrews** [comment]
Code pushed to master.
