### ISSUE TITLE
Integrating "Add Creator" to existing workflow

### ISSUE THREAD

**Issue by ddmilne** [GrandComicsDatabase/gcd-django#142]
We need a method to access the Add Creator screen from our regular workflow.  A poll of users 7/19/2016 found the following:
9 preferred the Option 3 presented: "Add Creator" button to appear on the page that appears when you currently hit the "Add New" button on your individual Editing screen.
4 preferred Option 3 WITH Option 4: "Add Creator" button to appear within any sequence you are editing.
1 preferred Option 3 with BOTH Option 4 and Option 5: "Add Creator" button to appear within the Editing group of buttons in the upper right corner of any Issue or Series display.

I would recommend we use Option 3 to get the integration started, and revisit this when programming resources allow, to consider additional locations.
- Don

**Comment by jochengcd** [comment]
This is done in the creators code for long, i.e. option 3. 

Other options can be discussed and considered whenever we integrate the creators table with sequence editing.
