### ISSUE TITLE
"Deactivated fields" no longer displays on the issue field edit page

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#144]
This is a field added to the form purely for its help text to explain the fields turned off at the series level.  It should appear after Keywords but before Comments.

**Comment by handrews** [comment]
This seems to be because this field is a hidden field where we just display the help text.  A similar field describing how to use the multiple on-sale-data fields is also missing (even though they are two slightly different hidden field types underneath).

Note that the problem is *not* the fields being added in the form's __init__() method, as non-hidden fields added in that same code show up just fine.

**Comment by jochengcd** [comment]
This is due to django 1.7, i.e. did we check it is working with 1.6 ?

**Comment by handrews** [comment]
It works in the 1.6 code with the 1.6 virtualenv.  I am trying out 1.6 virtualenv with 1.7 code on beta (should be possible to run) although I broke something else with a recent change) to see if that surfaces anything.  But I'm pretty sure it's 1.7.  There were definitely a number of internal forms stuff changed in 1.7 based on stackoverflow questions.  Such changes are why some forms have fields out of order as well.

**Comment by handrews** [comment]
Definitely caused by 1.7.  Running the current (1.7-compatible) code in the 1.6 virtualenv properly displays the fields' help text.

**Comment by handrews** [comment]
So... Previously, each widget had an is_hidden field which was independent of what type of HTML input element it used.

In Django 1.7 they decided to get "smart" and made is_hidden a read-only property that is true if and only if the HTML input type is hidden.  They did not bother to document this in the release notes.

The solution is to override the property method on a subclass that has a hidden input to return true anyway.  Then the form code will render it in line with the "normal" fields, which is the behavior we previously relied on anyway.  I'm not sure that what we're doing is the absolute best way to go about this but it definitely works and there's no reason to revisit the entire approach over this right now.  It's something we can look at if/when we decide to do custom form rendering for a better layout.

**Comment by handrews** [comment]
Fixed on beta.  Also needed to move the on sale date help to a different spot to get it picked up during form initialization.
