### ISSUE TITLE
required creator dropdown boxes

### ISSUE THREAD

**Issue by ddmilne** [GrandComicsDatabase/gcd-django#155]
Adding/editing information for creator records requires several choices that can be made via dropdown boxes.  These have been implemented with choices discussed on the committee and included in the specifications, but they may need to have additional choices added in the future.  Additionally, they should be checked to see if all choices from the specifications are present.

Choices that should currently be implemented for Source_Type are:
 Comic signature
 Comic credit
 Interview
 Legal document
 Creator questionnaire
 Creator’s records
 Publisher’s records
 News citation
 Book citation
 Internet citation
 Other media citation

Choices that should currently be implemented for Relation_Type are:
 Similar Name
 Owner
 Employee

Choices that should currently be implemented for Membership_Type are NOT yet determined.      From comments on the Policy list, it appears that folks would prefer to defer making a list, in favor of either using an expandable list or setting up some sort of additional organizational tables.  It's not urgent; we can just use the creators system as implemented by the contractor for now.  I believe it has the types of member, president, treasurer, and officer currently set up.  Others may be present in the existing Who's Who date; for example "executive director" appears.

Choices that should currently be implemented for Work_Type are:
 Book
 Magazine
 Newspaper
 Television
 Radio
 Movie: including videos
 Live Show: including theater work, speeches, and other performances
 Advertising
 Fine Arts: including sculpture, painting, musical composition, furniture, installation art
 Web Comics
 Internet Article
 Other: This might include things such as packaging, games, architecture, or industrial design.

Choices that should currently be implemented for Work_Role are:
 Owner
 Employee
 Art Director
 Artist
 Editor
 Animator
 Writer
 Set Designer
 Actor
 Voice Actor
 Assistant
 (and way too many more for me to figure out at the moment.  From discussions noted above on the Policy List, this may be another good place to use an expandable list because we do not know all the possibilities in advance. )

**Comment by jochengcd** [comment]
All or most of these roles exist in the dropdown.

If some are missing, please specify which.

**Comment by ddmilne** [comment]
To get things moving, perhaps we should simply use the lists above and wait for folks to propose additions under actual use conditions, and then add new roles as needed.  Or, as noted, this may be a good place to use an expandable list because we do not know all the possibilities in advance.

**Comment by jochengcd** [comment]
As said, all or most of these are in the dropdown. Please check when you do the testing.

These lists are expandable in the sense that admins can add to these, which we can do via the admin-functionality of django.

I am closing this then, if entries are missing please open a separate report.
