### ISSUE TITLE
Cover status section not always showing on my.comics.org

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#161]
[From Mike N. via mailing lists]
On My.comics.org, look at the Sandman Mystery Theatre series: http://my.comics.org/series/4657/

The cover status section doesn't show (using Chrome; also Firefox on Windows 7).

If you look at the trade series (still on my.comics.org) http://my.comics.org/series/24561/ the cover section does show.

Further debugging:
OK, I had thought it might be tied to the publication type since Sandman Mystery Theatre has that filled out and the trade series doesn't.

But I filled in the Action Comics Annual http://my.comics.org/series/69640/ publication type and it still shows correctly, so its not that.

**Comment by jochengcd** [comment]
http://reviews.comics.org/r/1743/
