### ISSUE TITLE
edit page for covers is broken

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#162]
http://www.comics.org/changeset/2813810/compare/
if one goes to
http://www.comics.org/changeset/2813810/edit/

we get an ISE. Likely to do with the changes which were done to the forms on the way to 1.7.

Internal Server Error: /changeset/2813810/edit/
Traceback (most recent call last):
  File "/opt/env/gcd-django/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/env/gcd-django/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/deployment/gcd-django/apps/oi/views.py", line 410, in edit
    form = form_class(instance=revision)
  File "/opt/env/gcd-django/lib/python2.7/site-packages/django/forms/models.py", line 312, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.

**Comment by handrews** [comment]
This change is now in the wrong state to edit. Is there a way to get to this error in the normal flow?

**Comment by jochengcd** [comment]
A cover can be sent back by the approver (but not retracted by the uploader). Created one here
http://beta.comics.org/changeset/3725712/edit/

**Comment by jochengcd** [comment]
Seemingly also is broken for other image uploads:

When an IMAGE is sent back (not rejected) and I attempt to view the change I get an Internal Service Error. This has happened for a cover upload that the approver thought might be on the wrong issue and for a statement of ownership I uploaded as an indicia.

**Comment by jochengcd** [comment]
covers is fixed for real, 

for images we do have a workaround, the underlying error happens deeper in django, unclear how to debug.
