### ISSUE TITLE
/download dump is over 15 days old

### ISSUE THREAD

**Issue by myers** [GrandComicsDatabase/gcd-django#165]
Usually you guys have a new dump up on the 1st and 15th, which really helps with a project I have at home.  There's no new update this month.  Is there a problem?

**Comment by handrews** [comment]
We changed several things about the deployment when we upgraded to Django 1.7 a few weeks ago, and one of those things broke the dump script.  I'm working on it right now as it happens :-)

I'm not sure quite when it will be up and running properly given the holiday weekend and some other stuff, but a few days or at most a week or two.  I thought our sysadmin made an interim dump by hand- I'll have to check on that.

BTW just in case you are not on the gcd-tech or gcd-tech-announce mailing lists, be aware that the gcd_country and gcd_language tables were renamed to stddata_country and stddata_language.  The ids used for foreign keys are still identical.

**Comment by handrews** [comment]
OK, he'd partially hotfixed the script, so I did the rest of the fix and ran it.  You should now be able to download a dump from today, and it should run fine on the 15th and after.

The real fix to keep us from breaking it the next time we rebuild the production deployment will take longer, but currently isn't blocking anything so I'm going to close this issue.

**Comment by myers** [comment]
Thank you!
