### ISSUE TITLE
Bug 642: Voting form displays even if you can't vote on that agenda

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#174]
Originally Opened: 2011-05-23 23:00 PST

While we do check the can_vote permission, there is also a permission that can be attached to an agenda specifically.  For instance, the board agenda requires the board permission.  We currently display the vote options and submit button on the ballot page even if the viewer lacks that permission.  However, this is still only a P3 because the user's vote will trigger an error and not be counted if they try to vote (see lines 248-254 of apps.voting.views for where this check occurs).

**Comment by jochengcd** [comment]
Users cannot reach vote pages they are not supposed to reach. 
If so, user cannot vote anyway, since we check permissions when submitting a vote.
