### ISSUE TITLE
Bug 645: issue_counts are off

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#176]
Originally Opened: 2011-05-31 03:32 PST

Something weird is going on with the issue count code:

The Brand counts are what I noticed first:

mysql> select b.parent_id, b.id, b.name, issue_count, count(_) from gcd_brand b
inner join gcd_issue i on b.id=i.brand_id where b.deleted=0 and i.deleted=0
group by b.id having count(_) != issue_count;
+-----------+-------+--------------------------------------------------+----------------+-----------+
| parent_id |  id   | name                                                       | issue_count | count(*) |
+-----------+-------+--------------------------------------------------+----------------+-----------+
|          54 |       1 | DC                                                           |           8184 |      8183 | 
|          78 |   106 | A Marvel Magazine [corner peeled back] |                 8 |          12 | 
|          78 | 3310 | A Marvel Magazine [plain text]                  |                 8 |           4 | 
+-----------+-------+---------------------------------------------------+---------------+-----------+
3 rows in set (2.03 sec)

I do not know how DC got off by one, but I created "A Marvel Magazine [plain text]" yesterday and used a bulk edit to move four issues from "A Marvel Magazine [corner peeled back]" to the new brand.  I have also added a number of other issues to the "corner peeled back" brand since then, which unfortunately muddies the issues a bit.  There has, however, been no change to the "plain
text" since that initial bulk move of 4 issues.  Somehow they ended up doubled (and since the "peeled back" variant is down by four, perhaps the subtraction was doubled as well- that would make more sense than most other options.

There's also a small problem with the Indicia Publisher counts:

mysql> select ip.parent_id, ip.id, ip.name, issue_count, count(_) from
gcd_indicia_publisher ip inner join gcd_issue i on ip.id=i.indicia_publisher_id
where ip.deleted=0 and i.deleted=0 group by ip.id having count(_) !=
issue_count;
+------------+---+--------------------+----------------+-----------+
| parent_id | id | name                 | issue_count | count(*) |
+------------+---+---------------------+---------------+-----------+
|            54 |  3 | DC Comics, Inc. |            2746 |     2745 | 
+------------+---+---------------------+----------------+----------+
1 row in set (0.93 sec)

and I'm willing to bet it's the same DC issue that causes the off-by-one in both places.

If there's no clear bug to be found, we should probably just cron a script to sanity check the counts on a daily basis.

I have not checked the series issue count, nor the publisher issue count or series count.  It seems likely that they are susceptible to whatever this problem is as well, whether they currently show it or not.

**Comment by jochengcd** [comment]
Refactoring oi-code will handle stats differently.
