### ISSUE TITLE
Bug 663: Counts of issues associated with a brand not increasing (possibly variant related)

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#182]
Originally Opened: 2011-07-03 20:23 PST

URL: http://www.comics.org/brand/24/

I added two issues to this brand but the count of the issues is still 0. I think it's likely related to the fact that both of the added issues are variants.

**Comment by jochengcd** [comment]
we need a general discussion, what issues/variant do we count.
