### ISSUE TITLE
Bug 698: IMP calculation for publisher change is incorrect

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#186]
Originally Opened: 2011-09-26 23:32 PST

URL: http://www.comics.org/changeset/1315824/compare/

IMP calculation for publisher change where there are brands and indicia publishers present that are being re-set is incorrect. The change above got a reported IMP value of 35, which is 17 for the brands being changed, 17 for the indicia publishers being changed and 1 for actually moving the series. There should just be 1 for the series move.

There are a few in the queue right now that show this.

Peter

**Comment by bookcats** [comment]
#115 duplicate
