### ISSUE TITLE
Bug 702: Moving cover to new variant problem

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#189]
Originally Opened: 2011-10-02 22:12 PST

URL: http://www.comics.org/issue/815735/

I was creating a variant for this issue.  I created the variant, moved the cover sequence, and was moving the cover to the new variant.  I clicked on the cover, and waited for it to load.  While the change was loading, the site crashed, and reported an unknown error.  

I went back to the issue.  The cover hadn't been moved, so I tried to move it again.  It said it couldn't be moved, because it was already reserved.  I discarded all the changes, and remade the variant issue.  When I tried to move the cover, it said the same thing.

This is my first bug report, so I apologize for any errors.

**------- Comment #1 From Jochen G. 2011-10-02 23:35:34 PST -------**
changed the reserved status of the cover, fixing the underlying bug is difficult

**Comment by jochengcd** [comment]
Should be fixed by the new transaction handling we need to do for django 1.8. 

If it occurs again afterwards, we need a new bug. This bug didn't happen since 2011....
