### ISSUE TITLE
Bug 716: Need tool to merge existing accounts

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#194]
Originally Opened: 2011-11-22 16:42 PST

In case the same person registers twice to www.comics.org and then uses both accounts, we need a way to move everything to one of the accounts and delete the redundant one.

Since this should happen rather infrequently, we could probably get away with a script that admins can run from the command line, without a web UI.

**------- Comment #1 From Jochen G. 2014-04-16 07:45:21 PST -------**
This is rare enough to be done by a script on the backend:

With old, new

for i in old.changesets.all():
    i.indexer=new
    i.save()
new.indexer.imps+=old.indexer.imps
new.indexer.save()
old.is_active=False
old.save()

**Comment by jochengcd** [comment]
not needed, done on the backend.
