### ISSUE TITLE
Bug 726: script to check for 'black' state

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#198]
Originally Opened: 2012-01-18 09:22 PST

Ideally we fix the underlying problem of db/server hickups between the reservation of an issue and the creation of the changeset. But for now we should have a script checking regularly for issues which are marked as reserved, but have no active revisions.

Can we do this with an exclude/filter after the first one finding the reserved ones ? Or only with the for-loop

issues=Issue.objects.filter(reserved=True)
for issue in issues:
    if issue.revisions.filter(changeset__state__in=[1,2,3,4]).count() != 1:
       do something

**Comment by jochengcd** [comment]
will be different with the new transaction handling
