### ISSUE TITLE
Bug 727: add variant links doesn't show for preview of base issue

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#199]
Originally Opened: 2012-01-18 20:14 PST

Forgot about this, the preview of the base issue for a variant doesn't show the added variant. Technically because the added variant issue doesn't exist at this stage, but it could link to the preview page of the variant. That would result in a mix of IssueRevisions and Issues there, which is the reason I didn't do that so far because I didn't see a nice solution.

**Comment by jochengcd** [comment]
fixed during refactor
