### ISSUE TITLE
Bug 741: Create bugzilla instance for Who's Who

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#205]
Originally Opened: 2012-07-02 23:24 PST

Please create an instance of bugzilla for the Who's Who.

We can create a new URL for it, such as whoswho-errors.comics.org or somesuch.

Set up can be similar to errors.comics.org.

Front page can be identical to errors.comics.org with these changes:

Title of page would be 'Who's Who of American Comic Books 1928-1999'

Include a disclaimer box as on errors.comics.org but with this text
(hyperlinked where appropriate):
"Dr. Jerry Bails' Who's Who of American Comic Books is being maintained and hosted by the Grand Comics Database (http://www.comics.org/).  At the present time we have not determined how we are going to address the issue of errors in Dr. Bails data, but we're aware (as was he) that errors exist.  We are currently collecting information re: such errors so that we may address them in some fashion at a future date."

Introductory text following can say:
"Welcome to the Who's Who error tracker." and then rest of page can match errors.comics.org.

**------- Comment #1 From Lionel English 2012-07-02 23:57:18 PST -------**
Actually, do we own the bailsprojects.com domain name?  If so, we can create errors.bailsprojects.com as the url for this error tracker.

**------- Comment #2 From Ralf Haring 2012-07-03 00:20:47 PST -------**
Yes, the GCD owns bailsprojects.com but the nameservers point at Jamal's hosting provider so I believe he would be the one to set up any subdomains.

**Comment by jochengcd** [comment]
This can be closed as it would be double work.

We will be having the editable creators data in our db in the not to distant future addressing such errors and the Who's Who will stay as is in any case.
