### ISSUE TITLE
Bug 746: Who's Who Integration / New creator tables

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#207]
Originally Opened: 2012-08-24 11:50 PST

According to the recent Board vote: http://www.comics.org/voting/ballot/137/
... we will adopt the committee report of 2/18/2012, to create creator tables within the GCD database. This shall comprise the 72 items under DATA STORAGE, and also the 10 items under Non-comics work.

The report is available in our wiki: http://docs.comics.org/wiki/Report_WhosWho_Committee

**Comment by jochengcd** [comment]
This is done.

We now track individual smaller issues for the existing creator code.
