### ISSUE TITLE
Bug 747: deleted variants show in counts

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#208]
Originally Opened: 2012-09-02 00:32 PST

URL: http://www.comics.org/issue/772251/

This issue had a variant which was deleted. 

We make an on the series the following to get the numbers in a fast db-way:

```
def active_base_issues_variant_count(self):
    issues = self.active_base_issues()
    issues = issues.annotate(variant_count=Count('variant_set'))
    return issues
```

Problem is the annotate, it counts all variants, so also deleted ones. I think one cannot do a filter here. What probably would work is using an extra-method and using SQL-code in that. Since I don't know SQL I won't look into this further.

**Comment by jochengcd** [comment]
fix with coming django 1.8 update
