### ISSUE TITLE
Bug 751: Dead Bulk Issue Edit Link for barcode/isbn searches

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#210]
Originally Opened: 2012-09-04 23:12 PST

The "Bulk Issue Edit" link found in the Issue Search Results page produces the following error:  "Something is wrong.  We don't really know what.  If the problem persists please let us know."

**------- Comment #1 From Alexandros Diamantidis 2012-09-05 00:11:31 PST -------**
More details: searching for ISBN or Barcode from the front page produces a list of issues, but the "Bulk Issue Edit" link which appears results in an internal server error with the following exception:

MultiValueDictKeyError: "Key 'logic' not found in <QueryDict: {u'isbn':[u'1234']}>"

It seems that either 'logic' should have a default value if it's not set (True or False doesn't matter in this case) or the "Bulk Issue Edit" link shouldn't appear in this case. BTW, 'logic' corresponds to the "Behavior" search control field.

**------- Comment #2 From Jochen G. 2012-09-05 06:15:18 PST -------**
This only applies for barcode/isbn searches from the search box. 

These are actually irrelevant for bulk edits, because you wouldn't use them as a filter for one of these (otherwise someone would have found this bug months before). So, dead link, but no real problem for practical purposes.

**Comment by jochengcd** [comment]
bug appears only theoretically, cannot do bulk edits on these anyway
