### ISSUE TITLE
Bug 771: Can't search for cover, issue cover keywords

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#216]
Originally Opened: 2012-11-21 19:18 PST

URL: http://www.comics.org/search/advanced/process/?target=issue_cover&method=icontains&logic=False&keywords=thanksgiving&order1=date&order2=series&order3=&start_date=&end_date=&title=&feature=&job_number=&pages=&script=&pencils=&inks=&colors=&letters=&story_editing=&genre=&characters=&synopsis=&reprint_notes=&story_reprinted=None&notes=&pub_name=&pub_notes=&brand=&brand_notes=&indicia_publisher=&is_surrogate=None&ind_pub_notes=&series=&series_notes=&tracking_notes=&issue_count=&is_comics=None&issues=&volume=&issue_title=&variant_name=&issue_date=&indicia_frequency=&price=&issue_pages=&format=&issue_editing=&isbn=&barcode=&issue_notes=&issue_reprinted=None&is_indexed=None

An advanced search for keywords with target issue_ocvers fails with an error message 'Please enter at least one search term or clear the 'ordering' fields. Ordered searches must have at least one search term.'

This search works also fails for covers with the same error.  

It works for stories.  

It also works for issues, series, publishers, indicia publishers, and brands (it returns 0 results, but doesn't produce an error message).

**------- Comment #1 From Jochen G. 2012-11-21 19:56:37 PST -------**
cover scans don't have keywords. 

A keyword search only works for the object the keyword is assigned to. This is a limitation of the keyword library we are using and will only be resolved with a solr based search.

**------- Comment #2 From Lionel English 2012-11-21 20:15:15 PST -------**
If I search for something, it doesn't make sense for the search to fail by telling me I'm not searching for something.

If I search for a publisher with the keyword 'thanksgiving', the search tells me that there are no publishers matching that criteria.  That's reasonable. There aren't any.  It tells me there aren't any.

If I search for covers with the keyword 'thanksgiving', then the search should also tell me that there are no covers matching that criteria.  That would be consistent.  Or, it should tell me I can't search for covers with keywords, so the users would at least understand what the error is.

I note, however, that if I search for covers with pencils by Jack Kirby I get 2200 results (http://www.comics.org/search/advanced/process/?target=cover&method=icontains&logic=True&order1=date&order2=series&pencils=jack+kirby),
despite the fact that cover scans don't have pencils.  That's because a search for covers actually searches sequences of Type 'cover' and returns the cover gallery associated with the matching sequences.  keywords should do the same (and can--there _are_ cover sequences with keywords, as can be seen with a story search).

Similarly, if I search for issue covers with script=Alan Moore, I get 800 hits, despite the fact that no cover scans have scripts.  That's because a search for covers of issues searches the sequence records, and then returns a gallery of covers associated with the issues those sequences belong to.  Keywords should do the same thing.  And, again, a keyword search of sequences _does_ work, so it should be possible to join those results with issues and then with covers in the same way that every other covers for issues search operates.

**------- Comment #3 From Jochen G. 2012-11-21 20:17:07 PST -------**
The wrong error message is a different bug :-)

**------- Comment #4 From Jochen G. 2012-11-21 20:19:16 PST -------**
And let me repeat: A keyword search only works for the object the keyword is assigned to. This is a limitation of the keyword library we are using and will only be resolved with a solr based search.

It is technically not possible to have the keyword field perform the same way like pencils, etc. It should, but currently cannot.

**Comment by jochengcd** [comment]
problem does not exist any more with the updated taggit we are now using
