### ISSUE TITLE
Bug 773: Spam Blank Error Reports

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#217]
Originally Opened: 2012-11-23 01:52 PST

We have been getting a large number of blank error reports that appear to be some sort of spam. There`s no content to any of the reports.

Would it be possible to not allow an error report to be filed unless there is some text in the comments field? I don't know if such a thing is possible in bugzilla.

**------- Comment #1 From Peter Croome 2012-12-02 22:40:17 PST -------**
I asked on the bugzilla irc channel and got this info:

The two suggestions are: captchas and blocking IP addresses if they are all the same. I don't know if captchas would help, since the accounts may be being made manually.

<gcd-peter> hi helpful people. I'm part of a comic indexing group that uses bugzilla to track errors found in our data from people. http://errors.comics.org/ the problem we are having is that spambots are entering "errors" on random issues with blank content. They seem to be setting up new accounts each time. Is there a setting to prevent an a bug from being filed without content. Here is an example:
http://errors.comics.org/show_bug.cgi?id=8346
<LpSolit> you cannot, but it would be easy for the bots to add a single character to by pass your restriction
<LpSolit> you should disable the accounts of the bots
<reed> LpSolit: we should add captcha support as an option feature
<LpSolit> to create an account or to file bugs?
<LpSolit> bug 619892
<bugbot> Bug https://bugzilla.mozilla.org/show_bug.cgi?id=619892 User Accounts, enhancement, --, ---, user-accounts, RESOLVED DUPLICATE, captcha for user registration
<reed> create an account
<gcd-peter> thanks LpSolit... unfortunately the bots are making new accounts each time, so disabling the accounts would be useless
<LpSolit> gcd-peter: to confirm the creation of your account, you must use the token you get by email
<LpSolit> so it must be a valid email address
<LpSolit> and someone has to use the token in the email
<LpSolit> I wonder if that's done manually
<LpSolit> (in which case the captcha won't help)
<LpSolit> gcd-peter: if all bots are from the same IP, you could blacklist this IP
<gcd-peter> i will find out if all the bots are from the same IP... that might be a solution.  I really don't understand why someone is setting a bot to do this. it's not redirecting users anywhere. the only link is to our database. maybe harvesting the emails of those of us who close the reports?
<gcd-peter> the accounts all seem to be gmail or a russian website (.ru) with random characters as the user name
<gcd-peter> im afraid i dont have access to the IP addresses myself... im just a user, not a tech guy...
<gcd-peter> thanks for the advice... i'll report it back to the tech team.

**Comment by bookcats** [comment]
I think this issue could be closed. We don't seem to get many of these anymore and we've got a way to deal with them manually when we do get them.

**Comment by jochengcd** [comment]
Doesn't seem to be a problem any more.
