### ISSUE TITLE
Bug 60: Migration DB Cleanup : Spanish names properly spelled

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#22]
http://dev.comics.org/bugs/show_bug.cgi?id=60
Reporter: @andresin 

Current name in DB => Corrected name

Credit: writer
"Rafael Marin"  => "Rafael Marín"

Credit: pencils/inks/color
"Sergio Aragones"  => "Sergio Aragonés"
"Ramon Bachs"  => "Ramón Bachs"
"Daniel Acuna"  => "Daniel Acuña"
"Solano Lopez"  => "Francisco Solano López"
"Francisco Solano Lopez"  => "Francisco Solano López"
"Alvaro Lopez"  => "Álvaro López"
"David Lopez"  => "David López"
"Julian Lopez"  => "Julián López"
"German Garcia"  => "Germán García"
"Juan Jose Ryp"  => "Juan José Ryp"
"Jesus Merino"  => "Jesús Merino"
"Jose Gonzalez"  => "José González"
"Jose Ortiz"  => "José Ortiz"
"Victor Santos"  => "Víctor Santos"
"Javier Rodriguez"  => "Javier Rodríguez"
"Roger Bonet Martinez" => "Roger Bonet Martínez"

**Comment by jochengcd** [comment]
whenever we go to creator records for the credits this will be handled in any case, no need to spend time on it before.
