### ISSUE TITLE
Bug 785: double approvals can generate double content

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#224]
Originally Opened: 2013-01-02 21:28 PST

URL: http://www.comics.org/changeset/1685150/compare/

Normally it shouldn't happen, but I guess when there are server hickups double approvals can go through. 

Solution is to use the new django1.4 capabilities for select for write (or whatever it is called)

Need to investigate if this happened more than twice (I see one other case)

For this I set the series to deleted by hand, the one double added series wasn't connected to a revision so the change history was off anyhow.

**Comment by jochengcd** [comment]
this should not be possible with the RevisionLocks
