### ISSUE TITLE
Bug 792: Add keywords support tables to the database dumps

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#226]
Originally Opened: 2013-03-05 14:10 PST

The taggit_tag and taggit_taggeditem tables, used to support keywords, need to be added to the database dump script (in $PUBLIC_SUPPORT_TABLES).

It's possible that the tables shouldn't go there as-is, or perhaps we need to add the django_content_type which is referenced from taggit_taggeditem via field content_type_id.

**Comment by jochengcd** [comment]
now that the keywords data is finally cleaned up, it is fine to have it in the dump. Needed django_content_type, otherwise the keywords would all point to the wrong object.
