### ISSUE TITLE
Bug 798: Move image use disclaimer

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#232]
Originally Opened: 2013-03-26 01:02 PST

On the issue detail pages please move the image use disclaimer ("Cover thumbnails are used for identification purposes only. All rights to cover images reserved by the respective copyright holders.") from the bottom of the page to underneath the image itself. If possible, add the text as ALT TEXT to the image as well.

Please add the text as ALT TEXT to images on gallery pages as well, and include the disclaimer at the bottom of these pages above the footer and nav bar.

And add the text as ALT TEXT on the Small/Medium/Large cover view pages, with the text also below the image and above the footer and nav bar.

The actual text can remain the same size and weight as it current is.

**------- Comment #1 From Jochen G. 2013-03-26 07:54:35 PST -------**
ALT TEXT is used to describe the content and function of an image. Its purpose is to show what would be seen if the image is not shown, e.g. in case of screen readers. A copyright notice in the ALT TEXT hinders that functionality.

**------- Comment #2 From Lionel English 2013-03-28 00:38:09 PST -------**
OK, scratch the part about the ALT TEXT then.

**Comment by BigBlueHat** [comment]
It's probably best to leave this in the footer, so it applies to all cover thumbnails used within the content anywhere. Otherwise gallery pages would be cluttered with repeated copyright disclaimers per image.
