### ISSUE TITLE
Bug 800: Advanced search with invalid issue range results in exception

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#233]
Originally Opened: 2013-03-28 14:11 PST

Searching for an empty issue range (for example, "2-1") results in:

TypeError: reduce() of empty sequence with no initial value                     

The bug is in handle_numbers() in apps/gcd/views/search.py. I think it makes sense to reverse such ranges, so that "2-1" gives the same result as "1-2"

**Comment by jochengcd** [comment]
This fails, but silently not with an error as reported here.

We won't support this.
