### ISSUE TITLE
Bug 813: allow use of either keydate or on-sale date in display

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#236]
Originally Opened: 2013-07-29 08:11 PST

This at least is relevant for series timeline, there one 'knows' how many on-sale dates exist.

We could also allow the switch for search results in chronological order, but there the result would (currently) by more 'random' in the sense that much more keydates exists overall then on-sale dates.

**Comment by jochengcd** [comment]
WiP
