### ISSUE TITLE
Bug 850: update issue indexed status when series become non-comics publication

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#251]
Originally Opened: 2014-08-31 09:10 PST

in rare situations a series with (partially) indexed becomes a non-comics series. Than we seemingly need to update the indexed status of the issues since some might be ten percent indexed (which is more than partially indexed).

**Comment by jochengcd** [comment]
When calculating indexed status, we do not check on is_comics_publication, so this should be fine.
