### ISSUE TITLE
Bug 855: bond links should sort by local/remote issue dates

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#254]
Originally Opened: 2015-03-03 09:23 PST

The new series bonds are awesome :-)

Of course I have found some corner cases.  In all such cases, the display order is wrong and could be fixed by the following:

Order first by the date of the issue in the series being displayed 
- When those are the same, further order by the date of the other issue 
- When issues are not specified, assume the last issue of the "from" series and the first issue of the "to" series.

Cases that would be fixed by this:
1.  http://www.comics.org/series/255/
   Cat-Man Comics (Temerson / Helnit / Continental, 1941 series): http://www.comics.org/series/255/
   Probably the most complicated set of links anywhere- a name change to lead in, a change to and then back from a different publisher, and a bizarre swapping of numbering schemes with another series.  There is one other series (Captain Aero) that has the same set of link conditions.  Plus Blue Beetle has the change-to-and-from-a-different-publisher type bonds, while All-Winners Comics has and internal numbering swap.  So while rare, these situations are not unique.

The order for Cat-Man should be
- from Crash Comics Adventures (T/H/C) #5 to Cat-Man Comics (T/H/C) v1#6 (1)
- from Cat-Man Comics (T/H/C) v1#10 (5) to Cat-Man Comics (Holyoke) v1#11 (6)
- from Cat-Man Comics (Holyoke) v3#7 (17) to Cat-Man Comics (T/H/C) v3#8 (18)
- from Cat-Man Comics (T/H/C) v3#8 (18) to Captain Aero Comics (T/H/C) v3#9 (11)
- from Captain Aero Comics (Holyoke) v2#4 (10) to Cat-Man Comics (T/H/C) v2#6 (19) [there is a gap in the dates for Captain Aero where the "missing" v2#5 would have appeared]
1.  http://www.comics.org/series/177/
   Daring Mystery Comics (Marvel, 1940 series) has two continuations.  First is a typical immediate continuation into another genre, with Comedy Comics.  But there was also later a re-launched Daring Comics that picked up the same numbering.  The Comedy Comics continuation should display first as it is earlier.

**------- Comment #1 From Henry Andrews 2015-03-03 09:24:26 PST -------**
I gave a link to the wrong Cat-Man.  The really complicated one is: http://www.comics.org/series/61787/

**------- Comment #2 From Jochen G. 2015-03-04 11:30:57 PST -------**
This is further complicated by the fact that issues might not have publication dates. So we probably need to fall back to series year in some cases.

I myself don't see a simple solution.

The routine to be changed is show_series_tracking in apps/gcd/templatetags/display.py. We don't actually need the 'direction' variable (for the problem outlined in this report), all should be done in the routine. 

**------- Comment #3 From Henry Andrews 2015-03-04 16:43:58 PST -------**
A good first approximation would be to sort by the issue order of the side of the links in the current series.  Really, the only time the dates come into play is when there are two links using the same issue (i.e. if you're looking at Daring Mystery Comics which is continued twice, both from the final issue).  In that case, it would be better if Comedy Comics displays first, but not the end of the world if it doesn't.

In the case of the Cat-Man example, just ordering the links by the Cat-Man issue involved would be tremendously helpful- no dates are needed to fix that example, really.

**------- Comment #4 From Henry Andrews 2015-03-06 08:20:53 PST -------**
I think I have a fix for this.  Need to actually get a test environment up and running for the first time in years...

**Comment by jochengcd** [comment]
This was (essentially) added a long time ago.
