### ISSUE TITLE
Bug 856: series bonds need to display issues for both ends

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#255]
Originally Opened: 2015-03-03 09:26 PST

For complex series bonds like Cat-Man Comics (http://www.comics.org/series/61787/ ) it's really necessary to see the issue number of the current series as well as the other series when both are available in order to make sense of things.  See bug 855 for a more exhaustive account of the bonds involved.

**------- Comment #1 From Henry Andrews 2015-03-06 08:40:16 PST -------**
Current proposal is:
numbering continues from #m with X #n 
numbering continues with #n from Y #m 

but only display the local issue if it is _not_ the last issue (for "from #m") / first issue (for "with #n")

**Comment by bookcats** [comment]
Bug 855 referenced is now #254

**Comment by jochengcd** [comment]
This was added a long time ago.
