### ISSUE TITLE
Bug 865: Deprecated sequence types appear

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#260]
Originally Opened: 2015-05-14 12:24 PST

If you are editing a sequence that is currently a deprecated type (like filler) you can change it to another deprecated type (like biography or unknown). 

If this isn't easily fixed to restrict the choices, maybe we could do what was done with Backcovers where it appears as Backcovers do not use.

**Comment by jochengcd** [comment]
changed, no old types will show any more
