### ISSUE TITLE
Bug 870: Add scan matrix for singletons is not clickable

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#262]
Originally Opened: 2015-07-21 03:25 PST

URL: http://www.comics.org/series/89176/scans/

Did a Series Name search for "Vader".  Got a list of series, as usual.  Several of the series do not have any covers loaded, so there is an "Add" link in the Covers column.  I wanted to upload a scan to "Vader's Little Princess", so I clicked the Add button, and got to the Scans screen with a scan matrix.  But there is nothing to click in the first column where the issue number would be.

I've since uploaded a cover for that singleton series, but this is reproducible by picking another singleton title on that list such as "De vreugde van het vaderschap".  Titles that are not singletons (such as "Van nul tot nu") work fine.

This was on Windows XP with Firefox, but I can also reproduce this with Firefox on Android, and with Chrome on Android.

**Comment by jochengcd** [comment]
fixed in dev version, to be deployed with creator changes
