### ISSUE TITLE
Bug 871: cannot change mentoring assignment for covers

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#263]
Originally Opened: 2016-01-06 13:56 PST

URL: http://www.comics.org/changeset/2603598/compare/

I recently adopted new user Johan Kjellstrom for mentoring but then dropped him and sent him back to the queue.  However, a large group of covers he submitted are now stuck in my approval queue.  These should be sent back to the general Pending queue or to his new mentor.

This appears to be a bug where covers are not reading the same information that other submissions are, as his issue indexing submissions were successfully transferred back to the general Pending queue.

**Comment by jochengcd** [comment]
When un-mentoring an indexer, no assigned changes are transferred back to the pending queue. Covers behaves the same as normal indexes. 

This is the expected behaviour.
