### ISSUE TITLE
Add a "not printed" checkbox to the volume field

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#267]
As per policy vote: http://www.comics.org/voting/ballot/253/

This vote authorizes the creation of a "Not Printed" check box attached to the Volume field. 

This allows the addition of the use of sources of potentially publisher-provided information not found in the comic book issue itself for the volume field.

Examples of such information could be (but not necessarily limited to); previous issue blurbs, house advertisements, publisher created promotional material, publisher websites, publisher corporate filings, paycheck stubs, original corporate or publisher documents, and copyright filings with the U.S. Copyright Office. 

When displayed the number shall appear in brackets. 

Detailed source information must be put into the Notes field to identify where the information came from and that it is not found in the original comic issue. This applies only to data reported by the publisher itself and not from fandom or creators where that information is handled differently. 

As needed, this same type checkbox can be added to other fields as applicable by a vote of the policy list.

Volume field rules to be adjusted to accommodate this new policy.

**Comment by jochengcd** [comment]
now in dev-version, will be deployed with creator changes
