### ISSUE TITLE
Reminder to open an issue on GitHub after a vote if Tech work is required

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#273]
I found a number of votes that require Tech work where a request for that work had not been opened as an issue. 

I see two solutions: 1) after the vote is complete, the user who opened the vote gets an additional email reminding them to open an issue here if needed
2) if Issues can be opened via email, the voting app sends an email to GitHub to open an issue if when the user started the vote they checked a new box stating "a yes vote will require tech work".

**Comment by jochengcd** [comment]
Honestly, I don't think it is too much to ask for the policy coordinators to evaluate after a vote if a tech ticket needs to be opened. It is part of that position. We all get automated emails after a vote, I don't see why another email would prompt the coordinator to act then all of a sudden.

**Comment by jochengcd** [comment]
Checking this is part of the policy coordinators job description.
