### ISSUE TITLE
Miscellaneous Creators integration needs

### ISSUE THREAD

**Issue by ddmilne** [GrandComicsDatabase/gcd-django#275]
1. On the page http://beta2.comics.org/creators/4/influence/add/ (Adding Creator Art Influence), the field "Self identify influences doc" should be renamed simply "Influences Notes".
2. On the page http://beta2.comics.org/creators/4/membership/add/ (Adding Creator Membership), an additional field for "Notes" is needed.
3. On the page Adding Creator Award (http://beta2.comics.org/creators/4/award/add/), an additional field for "Notes" is needed.
4. On the Creator Data View Page (http://beta2.comics.org/creators/4/), rearrange the image editing to work the same as our cover image editing.  That is: add "View: Large" and "Edit Image" links under the image, AND remove the buttons "Replace Portrait Image", "Delete Portrait Image", Replace Sample Scan Image", and "Delete Sample Scan Image".
5. Redesign the "Change History" link to look like our new standard.
6. Use the text on the various indexer Documentation pages linked from the bottom of http://docs.comics.org/wiki/Formatting_Documentation as the basis for Help messages on the indexing pages listed above.
7.  Implement our current policy for IMP assignment for the edits (see http://docs.comics.org/wiki/IMPs ).

**Comment by jochengcd** [comment]
Regarding 4. The creator images work as our other 'normal' images, i.e. scans of SoO and indicia, or the brand images. This is the normal behaviour.

Regarding 6. Please provide drafts for the actual help messages in a **separate** issue.

**Comment by jochengcd** [comment]
In the specifications there is no mention of the two Notes field for Membership and Award ?

**Comment by ddmilne** [comment]
Regarding the Notes fields for Membership and Award, is it possible that the Comments field is actually for Notes?  I assumed it was for our standard comments between indexer and approver, because of the name.  But could it be misnamed by the contractor?
If not, then the lack of Notes fields for Membership and Award was an oversight in the specs and we still need Notes.

**Comment by jochengcd** [comment]
comments are always comments.

**Comment by jochengcd** [comment]
1-3 and 5 are changed (at least locally)

4 is not to be changed

for 6,7 I added separate issues
