### ISSUE TITLE
"Page not found" page directs the user to bugzilla instead of here

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#277]
http://www.comics.org/series//add_issues/?add=Add+issues

The error page you get when you visit the above (for example) has a link to dev.comics.org instead of github.

**Comment by jochengcd** [comment]
With the bugzilla-link we could give the product (not needed here) and the location, i.e. the URL. 
http://dev.comics.org/bugs/enter_bug.cgi?product=GCD%20Online&bug_file_loc=http://www.comics.org/series/add_issues/?add=Add+issues
The later would be useful to automatically add to the description.

Anyone an idea if this can be done ? One can set a title with ?title=some_title to the URL
https://github.com/GrandComicsDatabase/gcd-django/issues/new
