### ISSUE TITLE
cover change history should appear inline on the issue history page

### ISSUE THREAD

**Issue by ralfharing** [GrandComicsDatabase/gcd-django#28]
On an issue's change history page, there is a link to a separate page for cover scan change history. This should appear inline all on one page.

**Comment by jochengcd** [comment]
[[461232d](https://github.com/GrandComicsDatabase/gcd-django/commit/461232dd5910eb817ad7bd96d45f386c130c1600)
#](https://github.com/GrandComicsDatabase/gcd-django/commit/461232dd5910eb817ad7bd96d45f386c130c1600)
