### ISSUE TITLE
wrong indexed status after story deletes/moves

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#289]
We have issues showing blue, although no stories exist any more, i.e. these issues had stories, but these were deleted.

My assumption right now is that sequences were deleted in bulk, and that using story.issue for the next one processed during deletion did fetch old issue data, so that it might look like sequences still existed ?

Since in the refactor also the stats stuff is newly done, which is related to this, check this for the new code and not worry about it in the current code base.

**Comment by handrews** [comment]
I'm pretty sure that the refactor addresses this and it is covered in the unit tests.  I vaguely recall noticing some unusual cases where this stuff would get out of sync.  But yes, let's leave this open until I can get back to that project and confirm.

**Comment by jochengcd** [comment]
should be handled by refactor
