### ISSUE TITLE
align sorting verbiage

### ISSUE THREAD

**Issue by ralfharing** [GrandComicsDatabase/gcd-django#29]
On the new search results page, you can sort by Relevance/Year/Country. If you drill into one of the filters, you can sort by Relevance/Alpha/Chrono/Country.

It's cosmetic, but Chrono and Year should probably be consistent. And is Alphabetic omitted on purpose?

**Comment by jochengcd** [comment]
Both are intentional.

year only uses year, chrono also month (i.e. keydate). Since the result can be different, we use different names, but could change this if wanted.

alphabetical cannot be done over different kind of search result objects.

**Comment by ralfharing** [comment]
I would probably just label them both "Date".
