### ISSUE TITLE
Add "Opt in for emails" to GCD New Accounts email

### ISSUE THREAD

**Issue by TRNaus** [GrandComicsDatabase/gcd-django#296]
Editors and members of the PR team receive an email for each new account registration. The information in the emails does not include the "Opt in for emails" making it difficult for the PR Team to reach out to the new registrants for more information. The current rate number of new account registration (about 95 a month) is a bit too high for the PR Team to search for each individual in the User List found in the Admin toolset.

Current information in the GCD New Accounts email includes: Name, Country, Language, Interests, and Where Heard from Us (this might want to be corrected as well).

**Comment by jochengcd** [comment]
Instead of 'might want to be corrected' it is even more helpful, if you give the correction

**Comment by TRNaus** [comment]
My apologies for the rabbit hole. The comment about correcting the phrase "Where heard from us" is not germane to the actual change requested.

**Comment by jochengcd** [comment]
Sigh, still, it can be correct, if it is noted what should be changed into what. What is obvious to one person, might not for others.

**Comment by jochengcd** [comment]
How about a tab for the prtream on the editing screen, under which they see all the users with opt-in set to true ?
