### ISSUE TITLE
Google Calendar Fix

### ISSUE THREAD

**Issue by hacklschorsch** [GrandComicsDatabase/gcd-django#301]
Google changed their calendar html code. It now needs one more change: including their domain. I'm not fluent in Python but this is what I do on my server since the recent change: 

    /bin/sed -i 's|<script type="text/javascript" src="/calendar/_/scs/|<script type="text/javascript" src="//www.google.com/calendar/_/scs/|'

**Comment by jochengcd** [comment]
Thanks for the pointer, will fix.
