### ISSUE TITLE
Add reprint button on issue editing page doesn't work without existing reprint note

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#304]
If you click the "add reprint" button next to each sequence on a page like https://www.comics.org/changeset/3020250/edit/ you get a bad page. The link is like: https://www.comics.org/story/revision/7404197/add_reprint/3020250/reprint_note//?reprint_7404197=Add+reprint

It works if there is a reprint note. If you manually put anything between the two //s it also works

I suspect it broke when the code to parse text reprint notes was fixed.

**Comment by bookcats** [comment]
#300

**Comment by jochengcd** [comment]
This worked locally just fine. I have a fix on production for now, but still want to understand why it doesn't work as it is.
