### ISSUE TITLE
cover approval flow should remember origin

### ISSUE THREAD

**Issue by ralfharing** [GrandComicsDatabase/gcd-django#38]
Right now the cover approval flow dumps the user onto the [pending cover page](http://www.comics.org/queues/covers_pending). However, if the user navigated there from the [regular pending queue](http://www.comics.org/queues/pending) it feels like you probably want to return there instead.

**Comment by jochengcd** [comment]
Not really. Typically if one approves a cover, one will approve more than just one, no matter from where one starts.

**Comment by ralfharing** [comment]
Typically if one is on a highway and gets off at an exit for a while, when they enter the highway again it is still the same highway.

**Comment by jochengcd** [comment]
If one takes the exit from highway 1 to highway 2 one usually stays on highway 2.

**Comment by ralfharing** [comment]
Users should wind up where they started. It's unexpected to dump them somewhere else. If they start on the cover approval page, by all means they should wind up back there.

**Comment by jochengcd** [comment]
While I agree with this in general, I don't here. Feel free to ask the editors on the editor list what they think, if people agree with you we can reopen this.
