### ISSUE TITLE
Spaces in issue level fields on issue creation

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#383]
I found spaces at the end of Publisher's Age Guidelines, Barcode and Editor, presumably they are not being stripped off when the issue is created.

Same as the Variant Name that I reported (and was fixed) last week.

**Comment by bookcats** [comment]
I did a .csv download of all the issues and found 1252 issues with spaces in one of the fields. Do you want me to fix them by running an imacro on them through the queue or is there something tech can do directly in the database?
[allspaces - Copy.txt](https://github.com/GrandComicsDatabase/gcd-django/files/2041060/allspaces.-.Copy.txt)

**Comment by jochengcd** [comment]
can't reproduce on beta, extra spaces are removed when saving a form
