### ISSUE TITLE
recording script of Creator's names

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#388]
as per https://www.comics.org/voting/ballot/329/

"It is hereby further moved that we add a field for capturing the name of the script used in recording the name, with the script names used to populate the field being drawn from ISO 15924. I further move that we add a similar field for capturing the name of the script used in recording Other Names, and that when both of these additional fields have been added that we thereafter use the native transcription of the creator's name as the official name, with a proper indication of the appropriate script, and that we require a Romanized transcription of the name as a required Other Name for all non-Latin names."

**Comment by jochengcd** [comment]
on beta
