### ISSUE TITLE
change history for creator sample scans

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#390]
needs to be added

**Comment by BigBlueHat** [comment]
Where would this appear and what data would it use?

**Comment by jochengcd** [comment]
On the change history of a creator
https://www.comics.org/creator/14169/
https://www.comics.org/creator/14169/history/

It would have entries for portrait and sample_scan, the appearance would be similar to the change history of an issue in regard to issue scans, e.g.
https://www.comics.org/issue/25165/history/
Therefore behave similar to these and similar in code.
