### ISSUE TITLE
Search for "Julie Schwartz" gets Internal Server Error

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#411]
Searching for either "Julie Schwartz" (with quotes) or Julie Schwartz (without quotes) returns an Internal Server Error. Adding anything (like "DC") gets a valid result.

I did just delete a creator record for "Julie Schwartz" which was showing up in the count of the results but then not showing up in the actual results. I also just added "Julie Schwartz" as a pen name for Julius Schwartz. I bet one or both of those is related.

**Comment by jochengcd** [comment]
search index us updated
