### ISSUE TITLE
Unable to edit fields added for "about comics" sequence

### ISSUE THREAD

**Issue by bookcats** [GrandComicsDatabase/gcd-django#417]
Maybe I'm just missing something obvious, but I got sent back an index with an "about comics" sequence because I had an error in the "abstract" field. I can't find how to edit the abstract, page numbers or that other field.

**Comment by jochengcd** [comment]
just edit the sequence ?

**Comment by bookcats** [comment]
Ramon talked me through it... you need to edit the sequence then hit the "save and return to changeset" button. Then you get the additional fields. Which wasn't intuitive to me.

Since the sequence type is already known when you edit an "about comics" type sequence, maybe the button name could be "save and edit about comics fields" (or something similar)?

**Comment by jochengcd** [comment]
No, we don't want to maintain type-specific buttons. Further, it is not really known, you can change the sequence type at that time.

You had the same workflow when adding the sequence, so it is just a matter of getting used to it.
