### ISSUE TITLE
UnicodeDecodeError when opening vote with non-ASCII title

### ISSUE THREAD

**Issue by adia** [GrandComicsDatabase/gcd-django#426]
When trying to open for voting a vote whose title contains a non-ASCII character, the following errors occur:

UnicodeDecodeError at /admin/voting/topic/add/
... and also:
UnicodeDecodeError at /admin/voting/topic/358/change/
'ascii' codec can't decode byte 0xe2 in position 76: ordinal not in range(128)
[...]
File "/var/deployment/gcd-django/apps/voting/models.py" in topic_post_save
  384.                 topic.deadline.strftime('%d %B %Y %H:%M:%S ') + settings.TIME_ZONE)

(but the error probably isn't directly related to this line)

**Comment by jochengcd** [comment]
not any more, likely fixed in some python/django upgrades
