### ISSUE TITLE
Bug 199: Actions on items in unexpected state cause error

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#44]
http://dev.comics.org/bugs/show_bug.cgi?id=199
Reporter: @adia

Trying to apply an action to an item (publisher, series, issue) which is in a
state the action doesn't apply causes an error. This can happen if you open the
item in two windows simultaneously and try to reapply an action after you have
already applied it. For example:
- Submitting an already submitted change
- Discarding an already discarded change
- Trying to re-edit a change already submitted or discarded

Not sure if it's worth it trying to fix this at this point, since I don't think
it can happen easily with normal usage, but opening a bug nevertheless.
------- Comment 1 From Henry Andrews 2009-11-30 04:16:16 PST [reply] -------
As long as you get an actual error page instead of a generic 500 error (the
"something went wrong" page) this is the expected behavior.  What else would
you expect the system to do?  (Re)Applying the action would be incorrect.
------- Comment 2 From Alexandros Diamantidis 2009-11-30 05:05:00 PST [reply] -------
Sorry, I wasn't clear: the error is indeed a 500 / internal server error
currently, not a normal error page, which is what I'd expect.
------- Comment 3 From Jochen G. 2009-12-02 16:58:07 PST [reply] -------
Why are raising ValueErrors if the states are not in expected states for
certain actions. 

This is fine for debugging and testing, but maybe this should go to the generic
error page on production ?
------- Comment 4 From Henry Andrews 2009-12-02 16:59:51 PST [reply] -------
Because I wrote that part a long time ago and hadn't sorted out any error
handling strategy.  It should all be updated to use render_error() or whatever
else is appropriate.
------- Comment 5 From Henry Andrews 2009-12-02 17:00:19 PST [reply] -------
Which might mean catching ValueError in the view layer, btw.  Not sure what
works best.
------- Comment 6 From Jochen G. 2009-12-02 17:18:27 PST [reply] -------
Probably better in the models.py. Some routines can raise ValueError for
several reasons.

We might want to make 

if settings.BETA:
    raise ValueError, text
else:
    render_error(text, redirect=False)

to still have debugging on dev.
------- Comment 7 From Henry Andrews 2009-12-02 18:00:18 PST [reply] -------
models.py should definitely not be aware of request objects or render_error(). 
That should happen exclusively at the view layer.  Even for testing, a good
error message is preferred over an exception, as it pinpoints a real case for
us instead of "oops, something unexpected blew up".
------- Comment 8 From Jochen G. 2009-12-04 05:04:23 PST [reply] -------
agree with models.py

for dev:
exceptions have the advantage that we will know about it, not just the tester.

so this would mean we have to write try everywhere in oi view code where the
model routines will get called ?
------- Comment 9 From Henry Andrews 2009-12-04 16:27:35 PST [reply] -------
About exceptions:  When it's a _correct_ error (i.e. the user tried to do
something that we know about and intentionally do not support, like edit a
change that's in the wrong state), as a dev I do _not_ want to know about it. 
It means that the code is doing what it should, which is returning an error.  I
only want to know if we've gone down a code path we did not anticipate with a
proper error message.

As far as try/except blocks, I'm not even sure that the validation that's being
done in the model layer belongs there.  Let's reconsider that aspect of the
design in kin-der-kids.  As Alexandros noted, for now it's not too critical
because if you get to this point you've done something odd anyway.  If we had
less time pressure I'd fix it before release but oh well.
------- Comment 10 From Ralf Haring 2009-12-04 16:48:51 PST [reply] -------
The case that brought this problem to light for me was two editors looking at
the pending queue trying to assign an item to themselves.
------- Comment 11 From Jochen G. 2009-12-04 16:55:35 PST [reply] -------
(In reply to comment 9)

> About exceptions:  When it's a _correct_ error (i.e. the user tried to do
> something that we know about and intentionally do not support, like edit a
> change that's in the wrong state), as a dev I do _not_ want to know about it. 
> It means that the code is doing what it should, which is returning an error.  I
> only want to know if we've gone down a code path we did not anticipate with a
> proper error message.

What I mean is that this distinction isn't always clear cut.

Anyway, let's look into this later. The changed cache behaviour on the queue
page will reduce the possible situations as well.
------- Comment 12 From Henry Andrews 2010-02-26 12:20:27 PST [reply] -------
**\* Bug 362 has been marked as a duplicate of this bug. ***
------- Comment 13 From Henry Andrews 2010-05-19 05:59:49 PST [reply] -------
**\* Bug 367 has been marked as a duplicate of this bug. ***
------- Comment 14 From Henry Andrews 2010-09-02 04:17:34 PST [reply] -------
**\* Bug 459 has been marked as a duplicate of this bug. ***
------- Comment 15 From Alexandros Diamantidis 2010-11-04 17:21:44 PST [reply] -------
Another source of errors of this sort I just encountered on beta: Open an issue
in two browser windows, press "Edit" on one, "Delete" on the other - result:
Internal Server Error. This only happens with indexed issues. With unindexed
issues, you are correctly informed that you can't do that because the issue is
reserved.
------- Comment 16 From Ralf Haring 2010-11-04 17:36:52 PST [reply] -------
by indexed vs. unindexed do you mean issues with and without sequences?
------- Comment 17 From Alexandros Diamantidis 2010-11-04 18:01:36 PST [reply] -------
Hmm... That's what I meant, but I hadn't actually done many tests, and now that
I try it again, I see that's not it.

I now tried this with some other issues, and the only one to exhibit the error
is:

http://beta.comics.org/issue/128584/
------- Comment 18 From Ralf Haring 2010-11-04 18:08:03 PST [reply] -------
I thought it might be a problem with single-issue series but others seem fine.
I tried that issue on beta and locally got the same error. It looks like it is
because of non-ascii characters in the series name. I tried some German issues
in series with umlauts and ß and got the same error.
------- Comment 19 From Ralf Haring 2010-11-04 18:53:38 PST [reply] -------
This actually occurs when you try to do Edit from two windows as well, so it's
not specific to Deletes.
------- Comment 20 From Ralf Haring 2010-11-04 20:38:56 PST [reply] -------
(In reply to comment 15)

> Another source of errors of this sort I just encountered on beta: Open an issue
> in two browser windows, press "Edit" on one, "Delete" on the other - result:
> Internal Server Error. This only happens with indexed issues. With unindexed
> issues, you are correctly informed that you can't do that because the issue is
> reserved.

This part of this bug is handled by http://reviews.comics.org/r/640 (part of
0.4 little-nemo). Not sure about the previously reported parts.

**Comment by jochengcd** [comment]
This is now fixed. We use ErrorWithMessage instead of ValueError now in the oi, these are all displayed with 'our' page instead of the generic error which for some rare cases still showed.
