### ISSUE TITLE
trying to add an issue under reprints

### ISSUE THREAD

**Issue by orlmac** [GrandComicsDatabase/gcd-django#452]
Occurred at 5:14 pm when trying to add The Ultimates (2004) #nn to The Ultimates #1 (2002).  I can get to where you select the issue when I get the problem.  Thank you for your help.  
Darrel

**Comment by jochengcd** [comment]
To what kind of sequence are you adding this ? Existing one ? New One ?

**Comment by jochengcd** [comment]
Not enough information to investigate further.
