### ISSUE TITLE
Bug 212: Additional add multiple options

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#46]
http://dev.comics.org/bugs/show_bug.cgi?id=212
Reporter: @handrews

Some good ideas on this from various sources:

From Ray via the main list:

--- quoting Ray --
It would be great to have the ability to add multiple issues on any series that
has no issue numbers, but we use instead some other option to identify the
issues.

I am thinking about those hundreds of weekly issues of any number of British
comics that have no issue numbers and we use the cover date as the defacto
issue number to identify the difference in issues. Often with stuff like
1964/03/03 [1], etc... as the issue number.

If there is anyways to automate stuff like that somehow, would help get a lot
more Brit books into the database.
--- end quote --

From Jochen in code reviews:
European series that skip numbers in a pattern, i.e. 1/1995, 3/1995, 5/1995...

From me:
Series that count backwards
Series that use predictable whole numbers on the cover with issue/volume in the
indicia, i.e. v2#1 [13], v2#2 [14], etc. although that won't be as much of an
issue in New Fun.  But that's a ways off as it's one of the more complex
changes.
------- Comment #1 From Mark Gordon 2009-12-09 13:27:39 PST [reply] -------
Gentlemen,
I've come across several series from the publisher EBAL that maintain issue
numbers relevant to the actual year published. What makes this most distressing
is several of these series jumps issue numbers or issue years. For example you
could have issues 1950 to 1954, then returning to 1962 to 1974, then ending
with 1979  and 1980.

I've listed these series simply as the years for issue numbers in hopes this
can be changed in the year 2010.

I will keep track of all series that I create with this particular exception
and return to it when the tech team is ready to write code to correct them.

Thank you.
Mark

**Comment by jochengcd** [comment]
too many special cases to do automatically
