### ISSUE TITLE
Unable to import comicbookdb export

### ISSUE THREAD

**Issue by daniel-lee-kruse** [GrandComicsDatabase/gcd-django#470]
Occurred at [My comics import](https://my.comics.org/import_items/).
The columns are:
Title	Issue Number	Issue Name	Variant Name	Publisher	Imprint	Cover Date Month	Cover Date Year	Cover Price	Condition	Quantity	Storage Method	Storage Location	Notes	Price Paid	Writer(s)	Penciller(s)	Inker(s)	Colorist(s)	Letterer(s)	Editor(s)	Cover Artist(s)	Tradeable	Sellable	Read/Unread	Date Acquired	Location Acquired

The _Import Issues Into A Collection_ dialog states the publishers are handled by their code.  It also states that some series and annuals need a search-and-replace done on them.  Is there information anyplace stating what needs to be done?
Thanks,
Daniel

**Comment by jochengcd** [comment]
The search-and-replace concerns the different publisher names between comicbookdb and the GCD, or the different series names. These need to be replaced in the text file for an import to be able. After an import you would see which lines weren't able to be processed.

In your case I see an error in the log:
'ascii' codec can't decode byte 0xef in position 4146:
So some characters give problems ?

**Comment by daniel-lee-kruse** [comment]
I attempted another import with the same vague message.  I attempted around 11:10 pm CDT.

**Comment by jochengcd** [comment]
can you send me the file ? There seems to be a problem with it, I would need to see it.

**Comment by daniel-lee-kruse** [comment]
Hi @jochengcd,
Since I'm uncertain whether or not you received the .csv file (I'm assuming it would be attached to this issue.) I have attached it here.  I see that .csv aren't supported attachments.  The .csv file is in the zip.
Thanks.

[a-collection-2019-12-10.csv.zip](https://github.com/GrandComicsDatabase/gcd-django/files/5208846/a-collection-2019-12-10.csv.zip)

**Comment by jochengcd** [comment]
There is a problem with the file encoding that resulted in the ISE. Made a change to the code, now it fails differently.

But, that is not a csv but a tab-separated file. You need to replace the tabs with commas ',', with that it works mostly, i.e. many issues can get identified.
