### ISSUE TITLE
Fix HTTP-to-HTTPS redirect of docs.comics.org

### ISSUE THREAD

**Issue by darylf** [GrandComicsDatabase/gcd-django#482]
Hello,

I made a PR to update the README's links to HTTPS (#481), but I just realized the technical error the links ar ethrowing might be caused by an error with the actual HTTP-to-HTTPS redirect configured on the server.

**Trying to visit:**
http://docs.comics.org/wiki/Main_Page#Technical_Details _(non-http)_ 

**Redirects to:**
https://docs.comics.org//wiki/Main_Page#Technical_Details _(note the 2 slashes before the path)_

**The intended landing page of the redirect should be:**
https://docs.comics.org/wiki/Main_Page#Technical_Details _(note the single slash)_

**Comment by adia** [comment]
Thanks, Daryl! I fixed the incorrect redirection in the docs.comics.org Apache config and merged your PR.
