### ISSUE TITLE
Looking to help out!

### ISSUE THREAD

**Issue by yuval-herman** [GrandComicsDatabase/gcd-django#526]
Hi there!,
I'm a newborn full-stack developer, but for a long time I saw your call for help in the front end department of the site.
Recently I've been studying new web technologies and I thought I could lend you a hand in here.

I'm familiar with the following technologies:

- HTML
- CSS/SCSS
- JavaScript/TypeScript
- Express.js/Node.js
- Python ( I touched flask but I wouldn't say I really know to use it)
- REST API's

I'm also still studying so soon I should learn to work with react as well.

So, if I'm interested in giving the site an overhaul with a new, modern look, where should I start?

**Comment by yuval-herman** [comment]
I see, I can definitely help with that!
I sent a request to join the gcd-tech mailing list through the link in the readme file.

**Comment by jochengcd** [comment]
did you join gcd-tech ? And set up a dev env ?

**Comment by yuval-herman** [comment]
Hi sorry for the silence...
I thought I could do it during my studies as a side project but it doesn't
seem like the pressure is easing up...
I will get to it if I manage, for now however, I did clone the project and
digged a bit here and there, I didn't notice a lack in responsiveness
however.
Everything seems to be scaling up and down relatively fine, could you send
me a specific url as an example to something you'd like me to work on?

**Comment by jochengcd** [comment]
Yeah, relatively thinks are scaling, but it isn't a nice experience.

E.g.
https://www.comics.org/searchNew/?q=batman&selected_facets=facet_model_name_exact:story
one needs usually to zoom on mobile, so one should have different sizes of the table. But if the table is larger, than on mobile one should think about the filters on the left being hidden at first to gain space. 

For the filters, one could think about extending their usage, e.g. not just one positive, but several, and pos/neg filters.

Also here
https://www.comics.org/series/name/batman/sort/alpha/
thinks could better, or we could also think about filters. Although this result page still needs updating to the 'blueish' result pages that allow sorting by columns, as in here:
https://www.comics.org/feature/name/batman/sort/alpha/

Where again, filtering would be nice...

Can/did you join the gcd-tech mailing list ? Discussion are better there.
