### ISSUE TITLE
where is the "retract and edit further" button described in the docs?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#532]
After submitting a change for approval, the docs say you can ["retract and edit further"](https://docs.comics.org/wiki/OI_Tutorial#What_if_I_Want_to_Make_a_Change_Before_it_Is_Approved?) while it is pending approval, but I never see this in the actual interface.  I have to add a comment asking the approver to send back to me, or discard all changes and start over.

**Comment by gcd-github** [comment]
That button is on your editing screen, 
https://www.comics.org/queues/editing/ .  At the far right of each issue 
you've submitted.

- Don Milne

**Comment by jochengcd** [comment]
I assume you are still under mentorship, then your submission are directly assigned to an editor. Retract and edit further works only for changed without an assigned editor.

**Comment by LegalizeAdulthood** [comment]
We should update the docs to reflect that while under mentorship, this button doesn't appear.

**Comment by gcd-github** [comment]
Done at 
https://docs.comics.org/wiki/OI_Tutorial#What_if_I_Want_to_Make_a_Change_Before_it_Is_Approved? 
.

- Don Milne
