### ISSUE TITLE
Provide search links for text credits, text features and text characters

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#542]
If a credit is linked, it takes you to the creators page where you can search for issues via the linked credits or via the text field.  Similar situations exist for linked features and characters.

Being able to navigate through features, characters and creators through the links is incredibly handy.

When those items exist only as a text field on a story, you can still do the search but you must manually copy/paste the field value into the advanced search form in order to find the necessary related items.

It would be more convenient if we could render the text fields as canned links to the advanced search functionality that would perform this search without having to copy/paste the data into the right place on the search form.

I'm not sure if this would generate additional server search load, however.

**Comment by LegalizeAdulthood** [comment]
If such links are provided, it would probably be best to render them distinct from existing linked creators/features/characters in order to make it easy at a glance to tell indexers which stories still need migrating.

**Comment by jochengcd** [comment]
Text based searches are error prone and expensive. We only want to easily support the db queries and not deprecated functionality.

**Comment by LegalizeAdulthood** [comment]
I see.  I've been mostly migrating credits (which furthers the goal you've stated) and had approvers say "migrating credits isn't that important", so maybe this goal needs to be popularized more `:)`

**Comment by gcd-github** [comment]
As an approver, I'm surprised you have had approvers say "migrating 
credits isn't that important".  All improvements to the data are important.

- Don Milne

**Comment by LegalizeAdulthood** [comment]
In all fairness to the approver, it was only once and it wasn't like my change was rejected, it was just mentioned off-hand in a conversation.

**Comment by LegalizeAdulthood** [comment]
At any rate, feel free to close this issue as "will not implement" for the reasons stated, with which I'm fine `:)`.

**Comment by gcd-github** [comment]
That doesn't sound so bad; thanks for the clarification.

- Don Milne
