### ISSUE TITLE
Migration of editing credits doesn't seem to be as smart as migrating story credits

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#543]
For instance, if the original editing field is:

> Alf Wallace [as Alf]; Bob Bartholomew [as Bart]

Then the migrate button doesn't do anything, whereas I would have expected it to migrate the name and put the "Alf" in the "Credited as" box and "Bart" in the "Credited as" box, like it does for story credits.

**Comment by gcd-github** [comment]
The problem with that approach is that our old text credits did not 
necessarily differentiate the meaning.  "[as Alf]" may have meant 
"credited as" OR "signed as".  It was decided not to assume anything.

- Don Milne

**Comment by LegalizeAdulthood** [comment]
So... it does the right thing with this in arts credits?

> Alf Wallace [as Alf] (credited)

I tried adding "(credited)" to the editor credits line before clicking migrate and it didn't pick that up.

**Comment by LegalizeAdulthood** [comment]
If someone can point me to the code where the edit credits are migrated, I'll poke around and see what I can find out.

**Comment by jochengcd** [comment]
this
    Alf Wallace [as Alf]; Bob Bartholomew [as Bart]
didn't migrate since Alf and Bart exist twice in the database. (the other Alf can be deleted though)

This example doesn't migrate for story credits either due to that.

Generally the 'as' does work for issue edits.

I deleted the other Alf, Alf Wallace [as Alf] now migrates for issue editing.
