### ISSUE TITLE
When migrating credits recognize localized versions of 'typeset' (and probably other magic words like 'various')

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#548]
Currently when migrating credits on a non-English language issue, if the letters field is set to a localized version of the word 'typeset', the credit migrator doesn't recognize this as a "migrated" credit.

If I switch the field to the English word "typeset", then it thinks the credit has been migrated.

However, reviewers said that they prefer to use a localized version of "typeset" for the foreign-language issues, so the software should recognize these localization conventions when migrating credits.  (Ideally it should even migrate "typeset" to the preferred localized equivalent.)

**Comment by jochengcd** [comment]
double of #522
