### ISSUE TITLE
Collapsed view user profile setting isn't honored on 'compare changes' link on the issue edit page

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#549]
Lots of times you're making a change to one story in an issue and you want to just see the collapsed compare view for your change.  Currently this requires two round trips to the server: once for compare changes and then again for collapsed view.  If we provided a collapsed view link on the issue edit page, we could get to the end result in a single round-trip to the server.

**Comment by ralfharing** [comment]
This can be controlled by the user as a default setting via their profile page. "Collapse compare view by default"

**Comment by LegalizeAdulthood** [comment]
I see.  Feel free to close this issue, then `:)`

**Comment by LegalizeAdulthood** [comment]
Hmm.... doesn't seem to be working when I click the compare link from the issue edit page?

I switched my default to collapsed, but it's still showing expanded and I have to click collapsed view again on the compare page.

**Comment by LegalizeAdulthood** [comment]
Yes, I see what's happening.  The profile setting is only controlling the link from my "editing" page, not from the edit issue page.

**Comment by LegalizeAdulthood** [comment]
I've updated the title of the issue to reflect this.

**Comment by jochengcd** [comment]
That is intentional. While editing the indexer should see the full issue before submitting.

**Comment by LegalizeAdulthood** [comment]
OK, then we're back to my original request, which is to provide a collapsed view link directly from the edit issue page.

**Comment by jochengcd** [comment]
Which would need to be a separate user option. At least some people prefer it as is.

The compare view was introduced mainly for finished changes, in particular with approvers in mind, not indexers still working on a changeset.

**Comment by LegalizeAdulthood** [comment]
A separate option is reasonable.  I've developed the habit of always looking at the compare view before submitting because I catch stuff there that I didn't see while migrating credits (like how it sometimes silently chooses the "alternate name" even though it isn't known that it is credited as such).
