### ISSUE TITLE
Provide 'retract and edit further' button when viewing diffs of submitted changeset

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#555]
Sometimes while viewing a diff of a submitted changeset, you see something you'd like to correct and it would be nice if you could do that directly from the diffs page.

This would remove an additional step of having to go back to your editing list and find the issue there in order to retract it.

**Comment by jochengcd** [comment]
That button is there on the compare page ?

**Comment by LegalizeAdulthood** [comment]
I'm not seeing it on the compare page, only on the 'editing' page
![image](https://user-images.githubusercontent.com/4270863/194972275-f5670714-a6a6-4cd7-8afc-b05f4b4bda08.png)
