### ISSUE TITLE
Can't migrate credits on cover of "non-comics issue"

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#563]
Any attempt to edit the credits results in an error saying "this can't have a cover" (but it already has a cover in the database).

**Comment by jochengcd** [comment]
Non-comics cannot have a cover sequence. 
One can squeeze one in by using add reprint, but that is in the end a bug.

**Comment by LegalizeAdulthood** [comment]
So what to do in this case where the original issue has a cover (that wouldn't be allowed to be added now, but it's there) with credits?

Should the cover sequence simply be deleted?
