### ISSUE TITLE
Date range searches use an open interval

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#564]
Consider this search that looks for the feature "Horsepower" from Dark Horse comics:

[Dark Horse text/promo Horsepower](https://www.comics.org/search/advanced/process/?target=sequence&method=icontains&logic=False&keywords=&title=&feature=Horsepower&job_number=&pages=&pages_uncertain=&type=20&type=16&script=&pencils=&inks=&colors=&letters=&story_editing=&first_line=&characters=&synopsis=&reprint_notes=&story_reprinted=&notes=&issues=&volume=&issue_title=&variant_name=&is_variant=&issue_date=&indicia_frequency=&price=&issue_pages=&issue_pages_uncertain=&issue_editing=&isbn=&barcode=&rating=&issue_notes=&issue_reprinted=&is_indexed=&in_selected_collection=on&order1=date&order2=series&order3=&start_date=1999-01-01&end_date=&updated_since=&pub_name=Dark+Horse&pub_notes=&brand_group=&brand_emblem=&brand_notes=&indicia_publisher=&is_surrogate=&ind_pub_notes=&series=&series_year_began=&series_notes=&tracking_notes=&issue_count=&is_comics=&color=&dimensions=&paper_stock=&binding=&publishing_format=)

Note that the start date is 1999-01-01 and it picks up stories from January, 2000.

Now change the start date to 2000-01-01 and you would expect the January, 2000 stories to still be picked up, but now they are omitted.

It appears that the search is using an "open interval" on the date and not a closed interval that includes the start date?

**Comment by LegalizeAdulthood** [comment]
I guess this is sort-of explained in the description for date searching at the bottom of the page, but an inclusive interval makes more sense to most people, e.g. searching for dates starting at 1999-12-31 to begin the search at 2000-01-01 seems weird.

**Comment by jochengcd** [comment]
using 2000-01-01 picks up January 2000 dates ?

https://www.comics.org/search/advanced/process/?target=sequence&method=icontains&logic=False&keywords=&title=&feature=Horsepower&job_number=&pages=&pages_uncertain=&script=&pencils=&inks=&colors=&letters=&story_editing=&first_line=&characters=&synopsis=&reprint_notes=&story_reprinted=&notes=&issues=&volume=&issue_title=&variant_name=&is_variant=&issue_date=&indicia_frequency=&price=&issue_pages=&issue_pages_uncertain=&issue_editing=&isbn=&barcode=&rating=&issue_notes=&issue_reprinted=&is_indexed=&in_selected_collection=on&order1=date&order2=series&order3=&start_date=1999-01-01&end_date=2000-01-01&updated_since=&pub_name=Dark+Horse&pub_notes=&brand_group=&brand_emblem=&brand_notes=&indicia_publisher=&is_surrogate=&ind_pub_notes=&series=&series_year_began=&series_notes=&tracking_notes=&issue_count=&is_comics=&color=&dimensions=&paper_stock=&binding=&publishing_format=

**Comment by LegalizeAdulthood** [comment]
I've since migrated the issues from January 2000 so they're not showing up in the search anymore....  Let me create another example

**Comment by LegalizeAdulthood** [comment]
OK, I found another January in the search results, this time for 2005.  I'll stop migrating these so the search results remain stable `:)`.  I added screen shots of what I see in the results for these two searches.

[Dark Horse text/promo Horsepower - Dec 31 2004](https://www.comics.org/search/advanced/process/?target=sequence&method=icontains&logic=False&keywords=&title=&feature=Horsepower&job_number=&pages=&pages_uncertain=&type=20&type=16&credit_is_linked=&script=&pencils=&inks=&colors=&letters=&story_editing=&first_line=&characters=&synopsis=&reprint_notes=&story_reprinted=&notes=&issues=&volume=&issue_title=&variant_name=&is_variant=&issue_date=&indicia_frequency=&price=&issue_pages=&issue_pages_uncertain=&issue_editing=&isbn=&barcode=&rating=&issue_notes=&issue_reprinted=&is_indexed=&in_selected_collection=on&order1=date&order2=series&order3=&start_date=2004-12-31&end_date=&updated_since=&pub_name=Dark+Horse&pub_notes=&brand_group=&brand_emblem=&brand_notes=&indicia_publisher=&is_surrogate=&ind_pub_notes=&series=&series_year_began=&series_notes=&tracking_notes=&issue_count=&is_comics=&color=&dimensions=&paper_stock=&binding=&publishing_format=)
![image](https://user-images.githubusercontent.com/4270863/197361028-5e78c50b-bc99-4912-ac8b-17fb20dbb4aa.png)

[Dark Horse text/promo Horsepower - Jan 01 2005](https://www.comics.org/search/advanced/process/?target=sequence&method=icontains&logic=False&keywords=&title=&feature=Horsepower&job_number=&pages=&pages_uncertain=&type=20&type=16&credit_is_linked=&script=&pencils=&inks=&colors=&letters=&story_editing=&first_line=&characters=&synopsis=&reprint_notes=&story_reprinted=&notes=&issues=&volume=&issue_title=&variant_name=&is_variant=&issue_date=&indicia_frequency=&price=&issue_pages=&issue_pages_uncertain=&issue_editing=&isbn=&barcode=&rating=&issue_notes=&issue_reprinted=&is_indexed=&in_selected_collection=on&order1=date&order2=series&order3=&start_date=2005-01-01&end_date=&updated_since=&pub_name=Dark+Horse&pub_notes=&brand_group=&brand_emblem=&brand_notes=&indicia_publisher=&is_surrogate=&ind_pub_notes=&series=&series_year_began=&series_notes=&tracking_notes=&issue_count=&is_comics=&color=&dimensions=&paper_stock=&binding=&publishing_format=)
![image](https://user-images.githubusercontent.com/4270863/197361061-1f1551c5-7a6e-43f1-8199-b21a0c33eae6.png)

**Comment by jochengcd** [comment]
now I get it, double of #132
