### ISSUE TITLE
"issues to be migrated" for Steve Ditko returns issues in which he has no credits

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#566]
I've been working steadily to migrate all Steve Ditko credits and I thought I was nearly done until suddenly the "issues to be migrated" link started reporting > 100 issues to be migrated again.  I started working through the list and yes, the first few had Ditko credits, but now there are many issues in the list that have no Ditko credit at all?

https://www.comics.org/creator_migrate_checklist/name/Steve%20Ditko/

As an example, Thunderbolt #59 is in that list and it has no Ditko credits that I can see:

https://www.comics.org/issue/21243/

![image](https://user-images.githubusercontent.com/4270863/197405745-e56858e7-9f88-4c20-812a-24d69f2b5636.png)

**Comment by jochengcd** [comment]
in the ads
https://www.comics.org/issue/21243/?show_all#1441670

**Comment by LegalizeAdulthood** [comment]
Ah... OK, makes sense now.  I didn't have expanded view on and that's why my `Ctrl+F` search didn't find it.
