### ISSUE TITLE
series 2672 - Issue #2 

### ISSUE THREAD

**Issue by Simone-tech-ITA** [GrandComicsDatabase/gcd-django#571]
Error I believe due to the special character:
"A" with accent "^".

Thanks
-Simone

**Comment by jochengcd** [comment]
what error ?

**Comment by Simone-tech-ITA** [comment]
Now works.
Didn't load the page.
-Simone

Il dom 20 nov 2022, 10:20 JochenGCD ***@***.***> ha scritto:
