### ISSUE TITLE
Comic issues giving internal server error.

### ISSUE THREAD

**Issue by jhunterjActual** [GrandComicsDatabase/gcd-django#573]
Occurred at 

https://www.comics.org/issue/297721/

https://wwwcomics.org/issue/1802355/

so far. 

Internal Server Error
Something is wrong. We don't really know what.
If the problem persists please [let us know.](https://github.com/GrandComicsDatabase/gcd-django/issues/new?body=Occurred+at+)

**Comment by jochengcd** [comment]
fixed
