### ISSUE TITLE
Expand localization to understand language differences between regions

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#576]
For example, Portuguese in Portugal and Brazil are divergent culturally and linguistically and will often have different translations for modern phrases.

Other examples are Chinese (simplified, mainland China) and Chinese (traditional, Taiwan), French (Canada) and French (France).

**Comment by jochengcd** [comment]
We follow the ISO language codes. If there is one for these we can add it. If not, we don't distinguish.
