### ISSUE TITLE
Credit notes are lost when adding a story as a reprint

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#579]
For instance, if an art credited is annotated "painted" or "painting", that annotation is lost on the reprint.  This only happens if the credit has already been migrated; if the credit has not been migrated, then the annotation is left intact on the text credit field.

**Comment by jochengcd** [comment]
This is intentional. The system cannot know if the annotation does persist to the reprint (or copy of the sequence, same workflow behind the scenes) or not. The indexer knows.

**Comment by jochengcd** [comment]
The bug is for the text credits, where we don't remove these annotations.

**Comment by LegalizeAdulthood** [comment]
Wouldn't it make more sense to allow the indexer to decide what to remove as inappropriate rather than just wholesale delete everything?

**Comment by LegalizeAdulthood** [comment]
Also, the "painting" annotation seems somewhat special and perhaps should be explicitly modeled?

**Comment by gcd-github** [comment]
The problem with that method would be that many (most?) times, the 
current indexer would not have both the original comic and the reprinted 
version.  In that case, he would not know whether credits had changed.  
To avoid the resulting errors, it seems better to me to carry over 
nothing, allowing the indexer to fill in anything he does know.

- Don Milne
