### ISSUE TITLE
Bug 395: autofill from db

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#58]
http://dev.comics.org/bugs/show_bug.cgi?id=395
Reporter @jochengcd 

Obvious that we want to do this at some point, but as obvious (to us tech
people at least) that we need the new db schema beforehand, this is just to
document that we want to have something in this regard.

Partly from email:

It could be also a big help, if each field's got "guessing system". When you
start to type something on a filed (any field, script/artist/editor etc.),
program would give some suggestions what it could be. 

Further, the website could use the existing tables. For example, if I'm adding
a new artist for Tung Metall, the program will already know which artists have
been added to Tung Metall. So, it'll suggest only those artist which are on
database under Tung Metall.

[There were more comments in Bugzilla, but they're all about things that were issues in JavaScript and autocomplete implementations at the time (five years ago)- this stuff is pretty standard these days]

**Comment by jochengcd** [comment]
on beta
