### ISSUE TITLE
Features with foreign language translations in [] don't migrate anymore

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#595]
Previously, if you copy/pasted 'La Chose [The Thing]' in the feature object box it would complete to the correct feature.  Now it does not.

We need some unit tests around feature migration to keep old use cases working.

**Comment by LegalizeAdulthood** [comment]
Are we talking about the same thing?  See attached screen shot of [this query](https://www.comics.org/search/advanced/process/?target=sequence&method=icontains&logic=False&keywords=&title=&feature=La+Chose+%5BThe+Thing%5D&job_number=&pages=&pages_uncertain=&credit_is_linked=&script=&pencils=&inks=&colors=&letters=&story_editing=&first_line=&characters=&synopsis=&reprint_notes=&story_reprinted=&notes=&issues=&volume=&issue_title=&variant_name=&is_variant=&issue_date=&indicia_frequency=&price=&issue_pages=&issue_pages_uncertain=&issue_editing=&isbn=&barcode=&rating=&issue_notes=&issue_reprinted=&is_indexed=&in_selected_collection=on&order1=date&order2=series&order3=&start_date=&end_date=&updated_since=&pub_name=&pub_notes=&brand_group=&brand_emblem=&brand_notes=&indicia_publisher=&is_surrogate=&ind_pub_notes=&series=&series_year_began=&series_notes=&tracking_notes=&issue_count=&is_comics=&language=fr&color=&dimensions=&paper_stock=&binding=&publishing_format=&indexer_old=4662) - the feature text value 'La Chose [The Thing]' is used all over the place.

![image](https://github.com/GrandComicsDatabase/gcd-django/assets/4270863/a9ea0223-b5cd-472e-a4dc-db6a68129ab5)

**Comment by LegalizeAdulthood** [comment]
The workflow that no longer works is to copy the text value of the feature field into the clipboard and then paste it into the feature object box.  Previously if the pasted value was 'La Chose [The Thing]', the correct feature 'La Chose (French)' would autocomplete.  Now it does not.

**Comment by jochengcd** [comment]
If you earlier pasted La Chose [The Thing] into the autocomplete, it cannot have autocompleted. There is no match for La Chose [The Thing] in the feature objects data. There is only La Chose which is not a match for La Chose [The Thing]. Try it on beta, where the earlier code is still running.

If you paste <local name> [english name] into the autocomplete and the corresponding feature object exists, it will work.
