### ISSUE TITLE
Features with disambiguation text don't migrate with credits

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#596]
'The Avengers [superhero]' doesn't automatically migrate, but it migrates manually when pasted in the feature object box.  Previously, if the disambiguating text was present, they would migrate along with the credits when the 'Migrate Credits' button was clicked.

More unit tests are needed around feature migration to prevent regressions on previously working migration paths.

**Comment by jochengcd** [comment]
There are zero sequences with The Avengers [superhero] as text features in our database ? For migration this is essentially a non-issue, disambiguation wasn't really used before the text credits, the []-brackets used in the feature field where for translations.

**Comment by LegalizeAdulthood** [comment]
If the feature is listed as 'Avengers', it won't automatically migrate.  However, if you type 'The Avengers [superhero]' into the feature object box, it will complete correctly to a single feature.

Because 'The Avengers' (or just 'Avenges') will **never** automigrate and because features must either all be text or all be objects, I'll often add the disambiguating text in the text field for multiple features when they must all be text so that when the other text features are finally created as objects, a single click of 'Migrate Credits' will migrate them all without ambiguity.

Another way to minimize the amount of manual editing (thus reducing sources of error) is to edit the text field for the feature to include the disambiguating text, e.g. 'Ghost Rider [occult]', before clicking the Migrate Credits button.  Previously, this would migrate the feature correctly and eliminate manual round-trips via AJAX to get the proper feature object populated.  When it is multiple features that need disambiguating text added to them, this saves considerable time and manual editing of the feature object field.  This is the functionality that no longer works and is a regression.

Aside:

Really, we are migrating features automatically as a side-effect of migrating credits.  Once all the credits are migrated, there is no automated way to migrate remaining features that have since had objects created for their text field.  Issue #547 addresses this and I have an implementation that I believe will work, but I need to test it locally before submitting a PR.  See my [migrate-feature branch](https://github.com/LegalizeAdulthood/gcd-django/tree/migrate-feature) for what I think will fix that open issue.

More work is needed to elevate migration of features to the same first-class citizen of migrating credits, but this would be a good start for automating the migration of the remaining orphaned text features that correspond to existing feature objects.  Many of them are letter column features that didn't get migrated with credits.

**Comment by LegalizeAdulthood** [comment]
A simpler way to think about it is that any text that automatically migrates should interactively migrate via the AJAX call made in the Feature Object field.
