### ISSUE TITLE
Feature migration is too eager

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#607]
This appears to be a regression in the feature migration behavior.

If the text feature is 'Masquerade', it is now automigrated to a feature whose text contains the substring 'Masquerade' when that is the only feature matching the substring.

In this example the chosen feature is 'Vampire the Masquerade' which is not the correct feature.

So in this case, the migration process takes correct feature text value and turns it into an incorrect feature object value.  Migration should always be conservative in what it generates and not turn correct data into incorrect data.

**Comment by jochengcd** [comment]
Either the migration behaves as the autocomplete (as was requested) or not. Right now, they use the same code. I don't see a real reason to change it back due to missing feature objects.
Migration is and was always meant to be an assistance tool.

**Comment by LegalizeAdulthood** [comment]
The problem is that it now subtly changes the feature from text that isn't an exact match and requires additional manual review in order to be sure that it didn't change the features incorrectly.

**Comment by jochengcd** [comment]
All feature migrations require manual review ?! 

Otherwise we would just run a script on the backend.

**Comment by LegalizeAdulthood** [comment]
The "migrate" button should only do correct migrations and not introduce false positives.  Otherwise, why not just migrate EVERYTHING by hand?

The intent of the code is to assist in the process, not corrupt the data in the process.

If it's not known to be correctly selecting an object for text, then it shouldn't select an object.

This is already the case when it migrates credits -- if the match is ambiguous it doesn't migrate.

It shouldn't be any different here.

**Comment by jochengcd** [comment]
I see these as migrations by hand, assisted by the system.'

We can go back to exact matches of the feature name, which then won't work regarding disambiguations in the text feature any more though.
