### ISSUE TITLE
Autocomplete of features should prioritize features of the same type first in the list

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#613]
If I am autocompleting a letters page feature, all features that are of type letters page should show first in the autocomplete list.  Same for advertising features and story features.  The total set of results is the same as now, only the ones most likely to apply are listed first.  Within each type they should still follow the current sort order.

**Comment by jochengcd** [comment]
Why should we change the behaviour to show features that cannot be selected ?

**Comment by LegalizeAdulthood** [comment]
We allow character features to be placed on advertisements, for instance Captain America can appear as a feature on a Hostess Twinkie advertisement.

I'm only asking for the order of the features returned by autocomplete to be changed.

**Comment by jochengcd** [comment]
I mainly considered letters page, where only letter page features are allowed anyway. For stories we only have story features as well, same for in-house columns.

But right, ads are the only sequence types where we might have two feature types. 

But in the way we do it (exact matches on top of the result list), I don't see how we can have further sortings.

**Comment by LegalizeAdulthood** [comment]
OK, that makes sense.  I didn't realize the restrictions were different on advertisements.  Thanks for the explanation.
