### ISSUE TITLE
When adding a series, you can't add a comment without submitting for approval

### ISSUE THREAD

**Issue by LegalizeAdulthood** [GrandComicsDatabase/gcd-django#618]
Sometimes questions come up in the comments and you'd like to respond but you can only add a comment by submitting for approval.  It needs an "Add Comment" button like when editing other changesets.

**Comment by jochengcd** [comment]
All add changes are supposed to be resolved quickly to avoid somebody else doing the same add. While there might be situations when there is time (not an add for a current comic), the proposed change would affect also adds for current comics where this would be a problem.
