### ISSUE TITLE
Recognize "(illustrations)" in credits as one of the things that doesn't need to be migrated

### ISSUE THREAD

**Issue by jhunterjActual** [GrandComicsDatabase/gcd-django#623]
Some editors prefer to credit unknown artists of illustrations in text articles as "? (illustrations)", an entry that turns on the "Migrate Credits" button in the edit interface. Can it be treated like "various" or "(photograph)" to leave the button off?

See https://www.comics.org/changeset/6889666/compare/

**Comment by jochengcd** [comment]
the notes for a credit are never considered.

Various or ? get filtered out, such as typeset and its common translation.

IMHO, in the specific example, illustrations doesn't even add information, various would be enough.
