### ISSUE TITLE
Bug 438: Character encoding errors in the database

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#63]
http://dev.comics.org/bugs/show_bug.cgi?id=438
Reporter: @adia 

Non-ASCII characters in many database entries have been misencoded, with the
result that they appear as other characters. The mistakes are not consistent,
with the result that a specific character in the database might stand for
various other correct ones, or might actually be correct as it is.

A discussion can be found here:

http://groups.google.com/group/gcd-tech/browse_thread/thread/5c990cc7c7a0af9e/20674b1927083f77

We might fix those mistakes either by running updates directly on the database:
there is a couple of scripts attached to the thread above that can be updated
for the current schema.

Alternatively, it might be better to use the mass change framework from bug 310 (now issue #49 ) when it's implemented.

**Comment by bookcats** [comment]
Also see #22

**Comment by jochengcd** [comment]
This is too old to still worry about.
