### ISSUE TITLE
Restrict character relations and group memberships to entities of the same language

### ISSUE THREAD

**Issue by jhunterjActual** [GrandComicsDatabase/gcd-django#650]
In the dropdowns for selecting characters or groups to be related, restrict the entries populated in the dropdown to those matching the language selected in the other. (If neither dropdown has a selection yet, use the full list and then filter once the other dropdown has a selection). Dutch-language character records shouldn't have a member relationship to English-language group records, for example.

**Comment by jochengcd** [comment]
duplicate of #636
