### ISSUE TITLE
Bug 504: Handle common 500 errors

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#76]
http://dev.comics.org/bugs/show_bug.cgi?id=504
Reporter: @handrews

We should try to catch exceptions from common sources like filesystem
operations, reading file data from an upload stream, etc. and show the user a
reasonably informative error message.  In order to do this, we need to handle a
few subtleties that are currently handled by Django when there is an exception:
- Transactions need to be rolled back
- Email needs to be sent to the sysadmin list
- Anything else?

We might want to handle this with some options to the render_error() function,
but there might be some better Django libraries for handling this now.  It's
worth some investigation and thought so filing this for a future release.

**Comment by jochengcd** [comment]
Happening by far too rare to worry about.
