### ISSUE TITLE
Bug 591: sort listings by columns

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#82]
http://dev.comics.org/bugs/show_bug.cgi?id=591
Reporter: @jochengcd 

one should be able to click on the columns in search results/listings to sort
by them.

so for series search results I would like to be able to click on
Publisher        Title           Year    and maybe # Issues 
and then have the sort according to that column.

There are one or two django extension around which can do that (also together
with pagination), I looked recently, this is what I bookmarked:
https://github.com/miracle2k/django-tables
https://github.com/directeur/django-sorting
http://djangosnippets.org/snippets/308/

No JavaScript involved in these. Which would be a different way to do this.

------- Comment #1 From Jochen G. 2011-01-01 13:44:38 PST [reply] -------
Had a look at the different django possibilities in the last days.

First, we have to change our pagination code in any case (also if we would do a
JavaScript solution). For django_sorting the actual slize of the queryset needs
to be taken after the sorting inside the template, so weed need an additional
tag or filter to solve, but no real problem. Or we switch to django_pagination
(although that lacks some options our current pagination code has, but these
can be added). If we would use django_tables we also need quite a few changes
for the pagination.

Second, are there any fundamental advantages in using a JavaScript solution ?
Django-based would be via a new page, with JavaScript it would be inside the
page, but db-query and traffic would be more or less the same I guess ? Other
differences ?

Third, we probably want to use multiple columns to define a sort order, e.g.
publisher, year, seriesname should be possible, as well as publisher,
seriesname, year, etc. All either ascending/descending. Here also the question
arises how to let the user define the order. Anyone knows about good examples
how to do this ?

django_tables and django_sorting have to two very different concepts. 

django_tables defines SortTables, either based on a model, or defined by hand.
In these one than can defined sort-order, but also let the user decide the
order interactively. Which means we have to change the view code and the
template code for every table. But sorting by multiple columns is supported in
principle. 

djano_sorting works in the template via tags. If the querystring includes
sort=something the queryset is sorted according to that field. No changes to
the views, only to the template. Makes this appear somewhat nicer. But, no sort
by multiple columns for now. 
One would need to put the order_by into the querystring. And into the tags.
Since the order_by includes quotation marks it is not obvious if this can
actually be done directly or if some kind of encoding is necessary (e.g.
field1.field2.field3). So, for sorting by multiple columns this would need to
be adapted (but doable).

To proceed:
- we need to decide if we want to go with django or javascript way
- we need to figure out (find good example of) a decent way for the user to
  define sort order using multiple columns

Note that in the advanced search one can define in the form further sort
options by columns not shown, that is another thing to consider.

**Comment by jochengcd** [comment]
starting to use django-tables2
https://github.com/jieter/django-tables2
