### ISSUE TITLE
Bug 602: Remind indexers that they need to add issues to empty series

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#86]
http://dev.comics.org/bugs/show_bug.cgi?id=602
Reporter: @adia 

As long as we can't add issues to a series simultaneously with series creation,
it's possible to forget to add issues to a new series after it is approved.

It would be nice to display a reminder to indexers when they have created a
series but they haven't added issues yet.

What I'm thinking of is a message in an indexer's editing queue, something
like:
"Some new series you have added don't have any issues yet; you should add them.
Click here for a list." (with a link to a list of those series)

Another option would be to send a periodic reminder by e-mail, but that's
probably too intrusive so we shouldn't do that.

------- Comment #1 From Henry Andrews 2011-01-03 00:33:53 PST [reply] -------
I'm against periodic emails, but if they have approval emails enabled, we could
include a link back and text suggesting that they might want to add issues.  It
should just go to the series page so that they can see if issues have been
added in the meantime, though.

------- Comment #2 From Donald Dale Milne 2011-01-03 03:17:11 PST [reply] -------
The single e-mail reminder to indexers when they have created a series but they
haven't added issues yet is an excellent idea.  Should be sent after approval
of the series.  I have been stuck by forgetting I added a series, or annoyed by
having to check back repeatedly to see if the series was approved yet.

------- Comment #3 From Jochen G. 2011-01-03 22:22:49 PST [reply] -------
The real solution would of course is implementing the adding of issues together
with the add of a series.

In that regard, adding a link to the approval email for series is the only
worthwhile change, if at all.

**Comment by jochengcd** [comment]
This would result in many often unneeded emails, which indexers would thereby learn to ignore.

Series lists for publishers can now be sorted by issue count, so it will be easy to identify series without now.
