### ISSUE TITLE
Bug 613: Provide sane reservation API

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#87]
http://dev.comics.org/bugs/show_bug.cgi?id=613
Reporter: @handrews

There is no easy way to reliably reserve something, and there should be. 
_do_reserve is the closest, but as can be seen in
http://reviews.comics.org/r/761/ you need to do a lot of additional work to
properly make use of it.

This should be factored out of the views and into either the models (maybe) or
a supporting package (probably).

**Comment by jochengcd** [comment]
fixed by the lock on objects
