### ISSUE TITLE
Bug 614: Revamp the preview system

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#88]
http://dev.comics.org/bugs/show_bug.cgi?id=614
Reporter: @handrews

The preview pages break every single release, because I did a horrible hack to
get them working near the very end of the vieux bois release when I realized
people really wanted them.

We should have a set of preview wrapper templates that use "with" statements to
adjust the preview objects accordingly and then call the regular item display
templates.  This may require some adjustments in the regular item display
templates.

One option might be that there are a set of core templates plus two sets of
wrappers- one that implements the current item display semantics and another
that implements previews.  Basically, these need to set up ways of accessing
the current object to display (the display object in the normal case, but the
revision object in the preview case) vs the current object from which to
generate link URLs (the display object in the normal case, and the target of
the revision object in the preview case- unless it's actually more complicated,
I forget).

This would be a nice project for anyone who wants to learn how Django templates
work.

**Comment by jochengcd** [comment]
Preview system can be based on field data copied, but not saved, from revision to model. 

For m2m-relations we need to do some work, can use PreviewModel(Model) for these cases, i.e. overwrite model methods/fields.

Done on refactor-branch for publishers and series.
