### ISSUE TITLE
Bug 619: users don't become member when passing 4000

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#90]
http://dev.comics.org/bugs/show_bug.cgi?id=619
Reporter: @jochengcd 

someone asked if he would need to do something to become a member after passing
4000. The automatic adding to the group didn't work for some reason. There are
currently two more users who recently passed 4000 and don't belong to the
members group.

For the one who asked I used 
indexer.user.groups.add(Group.objects.get(name='member'))
to update his status.

I don't see why

```
if self.imps >= settings.MEMBERSHIP_IMPS and \
      self.imps - value < settings.MEMBERSHIP_IMPS:
    self.user.groups.add(Group.objects.get(name='member'))
```

doesn't work ? It is the same call, and the if should be correct, or ?

There are a couple of users who probably recently made switch (between 4000 and
6000 imps). Can we get the creation date of many-to-many-relations ?

------- Comment #1 From Henry Andrews 2011-01-23 20:56:55 PST [reply] -------
eek!  Don't run code, just go into the admin UI and make them a member!

I don't know why the code doesn't work either.

------- Comment #2 From Alexandros Diamantidis 2011-01-24 00:46:03 PST [reply] -------
About the following line in indexer.add_imps()...

self.imps = models.F('imps') + value

... is it used for reasons of atomicity? I tried changing it to simply...

```
self.imps += value
```

... and it seems to work.

------- Comment #3 From Alexandros Diamantidis 2011-01-24 01:02:01 PST [reply] -------
Also, according to...

http://docs.djangoproject.com/en/dev/ref/models/instances/#updating-attributes-based-on-existing-fields

...you must reload the object in order to access the actual value that was
applied to the updated field when using an F() expression. Maybe something like
the following - I tested it and it also seems to work correctly:

```
def add_imps(self, value):
    old_imps = self.imps
    self.imps = models.F('imps') + value
    self.save()
    if (old_imps < settings.MEMBERSHIP_IMPS and
          Indexer.objects_get(pk=self.pk).imps >= settings.MEMBERSHIP_IMPS):
        self.user.groups.add(Group.objects.get(name='member'))
```

------- Comment #4 From Henry Andrews 2011-01-24 01:04:57 PST [reply] -------
That sounds about right.  Put it up for code review and I'll OK it :-)
And yes, it is for atomicity, although it's probably not much of a concern. 
However, we've found several things that shouldn't be much of a concern that
turn out to happen rather regularly, so I'd like to leave it in.  This looks
like a good solution.

------- Comment #5 From Alexandros Diamantidis 2011-01-24 01:11:44 PST [reply] -------
Now that I think about it, we could just do:

```
if (old_imps < settings.MEMBERSHIP_IMPS and
    old_imps + value >= settings.MEMBERSHIP_IMPS):
```

The worse that could happen in a race condition between two approvals would be
to add the indexer twice to the members group, but there's no harm in that.

------- Comment #6 From Jochen G. 2011-01-24 08:08:14 PST [reply] -------
(In reply to comment #5)

> Now that I think about it, we could just do:
> 
> ```
> if (old_imps < settings.MEMBERSHIP_IMPS and
>     old_imps + value >= settings.MEMBERSHIP_IMPS):
> ```
> 
> The worse that could happen in a race condition between two approvals would be
> to add the indexer twice to the members group, but there's no harm in that.

But what could happen is that the user doesn't get added to the group.

If old_imps + value < settings.MEMBERSHIP_IMPS for both actions in the race but
old_imps + both value is larger.

Or ?

------- Comment #7 From Henry Andrews 2011-01-24 08:28:52 PST [reply] -------
Hmm.... I thought the code submitted for review solved this, but there is
probably a transaction problem here again.  Indeed, if two changes are being
approved at once, it's possible for the transactions to work out such that one
(or theoretically n - 1 out of n concurrent changes) will get their imps
dropped.

transactions are awesome except when they suck.

------- Comment #8 From Alexandros Diamantidis 2011-01-24 08:39:55 PST [reply] -------
Jochen is right - I thought about that problem just after writing comment #5.
That's why the review (now committed to svn) is for the change in comment #3.

http://reviews.comics.org/r/770/

------- Comment #9 From Henry Andrews 2011-01-24 08:46:52 PST [reply] -------
Unfortunately, while I agreed with you in the review at the time, now I'm not
so sure.  Consider this:

initial IMP value:  3990
Change 1 value: 9
Change 2 value: 7

START TRANSACTION ONE
[T1 see IMPS at 3990]
START TRANSACTION TWO 
[T2 sees IMPS at 3990]

T1: SET imps = imps + 9;
T1: SELECT \* from gcd_indexer WHERE id=<whatever>;
[T1 sees IMPS at 3999]

T2: SET imps = imps + 7;
T2: SELECT \* from gcd_indexer WHERE id=<whatever>;
[T2 sees IMPS at 3997]

T1: COMMIT
[3999 is comitted value. Not member]

T2: COMMIT
[3997 is committed value.  Not member, and 9 IMPs got lost]

I think this is what would happen, because I think that imps = imps + N is done
purely within the view of the transaction.

If I'm right, this bug needs to be reopened.  But I'm pretty tired and have
gotten this wrong at least once already, so I'll wait for a 2nd opinion.

------- Comment #10 From Jochen G. 2011-01-24 08:55:03 PST [reply] -------
We are using the F() construct, so we don't have problems with the adds since
the db does the actual add. The imps wouldn't get lost.

But it seems one needs to get a fresh query of the db the see the new value.
Which is a bit strange come to think of it, since the transaction behaviour
would work differently when one uses F() since one gets the a new value which
might depend on other transactions...

------- Comment #11 From Henry Andrews 2011-01-24 08:57:15 PST [reply] -------
I'm pretty sure the F works _within_ the transaction.  So it changes the field
based on the field's value within the transaction, and then the result gets
committed. Which is why the result is consistent with the read, and the
overlapped transaction's add is dropped.  I'd have to run a test to prove it,
and I'm going to opt to go to bed instead as I'm trying to get up early
tomorrow :-)  if no one in another time zone does it by tomorrow evening
(Pacific) I'll poke at it then.

------- Comment #12 From Jochen G. 2011-01-24 09:04:42 PST [reply] -------
(In reply to comment #11)

> I'm pretty sure the F works _within_ the transaction.  So it changes the field
> based on the field's value within the transaction, and then the result gets
> committed. 

But that is not how we are using in other updates. F() is an add on the
db-level.

from:
http://docs.djangoproject.com/en/dev/ref/models/instances/#updating-attributes-based-on-existing-fields

This approach doesn't use the initial value from the database. Instead, it
makes the database do the update based on whatever value is current at the time
that the save() is executed.

------- Comment #13 From Henry Andrews 2011-01-24 09:36:03 PST [reply] -------
Yes, but the save() method is executed _WITHIN_ the transaction.  It's just an
UPDATE.

BEGIN;
SELECT \* FROM gcd_indexer WHERE id=42;
UPDATE gcd_indexer SET country_id=123, ..., imps=imps+9 WHERE id=42;
COMMIT;

instead of the UPDATE being:
UPDATE gcd_indexer SET country_id=123, ..., imps=3999 WHERE id=42;

Either way it's still inside the transaction, and the thing that is committed
is the _result_ of the transaction.

As far as I know, transactions commit final state.  That is why the SELECT
reads in the middle of the transaction (for instance between the UPDATE and
COMMIT are consistent with the state of the database at the instant the
transaction is committed.

------- Comment #14 From Jochen G. 2011-01-24 10:13:29 PST [reply] -------
To clarify (for myself at least), there are two things happening here:

The update of the imps. That works fine with transactions, since the actual
real db save of an update of the current imp by value is at the end of the view
at the final commit. That is why we are using the db to do the add with F(), no
imps are getting lost.

The check if due to the update we cross the threshold. That seemingly doesn't
work since another process can update the value as well. But due to the
transaction handling each update only sees its 'own' updated value, which
doesn't cross the threshold. Only on the final commit of both updates the value
crosses the threshold, but both changes won't see that since for them the view
of the db is consistent and the threshold not crossed.

Only way around this I see is doing something similar to the update of the
reserved status and use a different transaction handling here. 

The member status is only needed for elections, right ?
Or policy votes as well ?

------- Comment #15 From Henry Andrews 2012-12-30 07:15:06 PST [reply] -------
I think SELECT...FOR UPDATE solves this.  Even within transactions, the READ
causes any other READ to block until the first transaction that reads commits.

**Comment by jochengcd** [comment]
closing, since 2011 no occurrence of this problem
