### ISSUE TITLE
add_creator() doesn't handle non-logged-in user

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#95]
To reproduce:  Bring up a clean environment on the creators2 branch (edit puppet/environments/local/site.pp and change the branch setting from "master" to "creators2" after checking out the vagrant repo but before running "vagrant up").

Load the URL http://localhost:8000/creators/add/ without logging in first.

Here is the error message (NOTE that "AnonymousUser" is a Django class, and does _NOT_ refer to our user that is named "anon").

```
AttributeError at /creators/add/
'AnonymousUser' object has no attribute 'indexer'
Request Method: GET 
Request URL:    http://localhost:8000/creators/add/
Django Version: 1.4.22
Exception Type: AttributeError
Exception Value:    
'AnonymousUser' object has no attribute 'indexer'
Exception Location: /opt/virtualenv/local/lib/python2.7/site-packages/django/utils/functional.py in inner, line 185
```

Here is the relevant bit of code, with the specific line marked with a '*'

```
 4691  /vagrant/www/apps/oi/views.py in add_creator
 4692          'method': request.method,
 4693          'timestamps': timestamps,
 4694          'form': form,
 4695        },
 4696        context_instance=RequestContext(request))
 4697  def add_creator(request, template_name='oi/creators/creators.html'):
*4698      if not request.user.indexer.can_reserve_another(): ...
 4699          return render_error(request, REACHED_CHANGE_LIMIT)
 4670      if request.method == 'GET':
 4671          creator_form = CreatorRevisionForm()
 4672      elif request.method == 'POST':
```

Presumably, since user.indexer is a GCD-specific thing, the built-in Django AnonymousUser object doesn't know about it.  This method either needs to require login or handle the non-logged-in state.  Probably require login.

**Comment by jadavbheda** [comment]
Hi handrews,

I have fixed the issue and as it is very few lines of code I have not created a review for this.

https://github.com/GrandComicsDatabase/gcd-django/pull/100

Please review the pull request.

**Comment by jochengcd** [comment]
long fixed
