### ISSUE TITLE
Creator month fields need to be drop-down

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#96]
The month fields on the creator add page are text widgets, but do not accept month names.  It's more typical to use a drop-down menu for months (and easier than handling all of the different ways people might try to enter months in a text field).

**Comment by jadavbheda** [comment]
Hi handrews,

I have added a dropdown for month entry as suggested.

https://github.com/GrandComicsDatabase/gcd-django/pull/101

Please review the pull request for the same

**Comment by ddmilne** [comment]
Resolved in final submitted code.  Tested 6/3/2016 by Don Milne.
